export { OffersPage } from "./offers/OffersPage";
export { DocumentsPage } from "./documents/DocumentsPage";
export { PaymentsPage } from "./payments/PaymentsPage";
export { CustomerBalancesPage } from "./finance/CustomerBalancesPage";
export { DueDatesCalendarPage } from "./finance/DueDatesCalendarPage";
export { AccountingInvoicesPage } from "./finance/AccountingInvoicesPage";
export { StockPage } from "./stock/StockPage";
export { ServiceRequestsPage, ServiceKanbanPage } from "./service/ServicePages";
export { MachinesPage } from "./machines/MachinesPage";
export { SettingsPage } from "./settings/SettingsPage";
export { PurchaseOrdersPage } from "./purchase/PurchaseOrdersPage";
export { ShipmentsPage } from "./logistics/ShipmentsPage";
export { InstallationsPage } from "./logistics/InstallationsPage";
export { DeliveriesPage } from "./logistics/DeliveriesPage";
export { ReportsPage } from "./reports/ReportsPage";
export { UsersPage } from "./admin/UsersPage";
export { RolesPage } from "./admin/RolesPage";
export { DepartmentsPage } from "./admin/DepartmentsPage";
