/**
 * CNC tezgah referansları — "Referanslar.pdf" tablosunun statik veri seti.
 *
 * Referanslar sayfası bu listeyi doğrudan gösterir; ana firma listesini ve
 * kurulu makine envanterini kirletmemek için ayrı tutulur. Tarihler ISO
 * (YYYY-MM-DD) biçimindedir; kaynak PDF'te Türkçe uzun tarih kullanılmıştır.
 */
export type ReferenceEntry = {
  no: number;
  firm: string;
  contact: string;
  district: string;
  city: string;
  brand: string;
  model: string;
  /** Teslim tarihi (ISO YYYY-MM-DD). */
  deliveryDate: string;
};

export const cncReferences: ReferenceEntry[] = [
  { no: 1, firm: "SÖNMEZ PLASTİK KALIP", contact: "Cemal SÖNMEZ", district: "Bayrampaşa", city: "İstanbul", brand: "AGMA", model: "VMC-115", deliveryDate: "2005-01-31" },
  { no: 2, firm: "YILSAN VANA", contact: "Ali OKTÜRK", district: "Pendik", city: "İstanbul", brand: "VOUGA", model: "CK-6140S", deliveryDate: "2005-03-09" },
  { no: 3, firm: "ÖNDER LİFT", contact: "Bekir Bey", district: "Salihli", city: "Manisa", brand: "VOUGA", model: "CK-6140S", deliveryDate: "2005-04-29" },
  { no: 4, firm: "KÖRFEZ MAKİNA", contact: "Alparslan KAYIŞ", district: "Gölcük", city: "İzmit", brand: "VOUGA", model: "CK-6140S", deliveryDate: "2005-05-23" },
  { no: 5, firm: "AYTANÇ KONVEYÖR", contact: "Ali Ulvi AYTANÇ", district: "Arnavutköy", city: "İstanbul", brand: "VOUGA", model: "CK-6140S", deliveryDate: "2005-09-05" },
  { no: 6, firm: "ZİRVE-BİR KALIP", contact: "Remzi SOYLU", district: "Pendik", city: "İstanbul", brand: "AGMA", model: "VMC-115", deliveryDate: "2005-10-22" },
  { no: 7, firm: "ZİRVE-BİR KALIP", contact: "Remzi SOYLU", district: "Pendik", city: "İstanbul", brand: "AGMA", model: "VMC-115", deliveryDate: "2006-03-27" },
  { no: 8, firm: "CİBO METAL", contact: "Murat CİBO", district: "Pendik", city: "İstanbul", brand: "VOUGA", model: "CK-6140S", deliveryDate: "2006-08-18" },
  { no: 9, firm: "ZİRVE-BİR KALIP", contact: "Remzi SOYLU", district: "Pendik", city: "İstanbul", brand: "AGMA", model: "VMC-115", deliveryDate: "2006-11-28" },
  { no: 10, firm: "ISITAN MAKİNA", contact: "Serkan ŞAHİN", district: "Osmangazi", city: "Bursa", brand: "AGMA", model: "VMC-115", deliveryDate: "2007-03-14" },
  { no: 11, firm: "ŞAHİNTEK PVC MAKİNA", contact: "Tekin ŞAHİN", district: "Nilüfer", city: "Bursa", brand: "AGMA", model: "VMC-115", deliveryDate: "2007-03-27" },
  { no: 12, firm: "ZİRVE-BİR KALIP", contact: "Remzi SOYLU", district: "Pendik", city: "İstanbul", brand: "AGMA", model: "VMC-2210P", deliveryDate: "2007-10-26" },
  { no: 13, firm: "AKTİF MAKİNA", contact: "Gültekin Bey", district: "Bayrampaşa", city: "İstanbul", brand: "VOUGA", model: "CK-6140S", deliveryDate: "2007-12-18" },
  { no: 14, firm: "AKSAN AKASYA MAKİNA", contact: "Yalçın ÜLKER", district: "Pendik", city: "İstanbul", brand: "VOUGA", model: "CK-6140S", deliveryDate: "2008-04-18" },
  { no: 15, firm: "DİSPA MAKİNA", contact: "Süleyman DABAN", district: "Nilüfer", city: "Bursa", brand: "AGMA", model: "VMC-158G", deliveryDate: "2008-05-02" },
  { no: 16, firm: "BİRSAN CAM KAPI", contact: "İbrahim AYDIN", district: "Bayrampaşa", city: "İstanbul", brand: "VOUGA", model: "CK-6140S", deliveryDate: "2008-06-13" },
  { no: 17, firm: "TEKNİK TAKIM", contact: "Seçkin KULU", district: "Sultanbeyli", city: "İstanbul", brand: "AGMA", model: "VMC-115", deliveryDate: "2008-07-30" },
  { no: 18, firm: "KADIRGA END.MSL.LİSESİ", contact: "Şükrü ERSOY", district: "Fatih", city: "İstanbul", brand: "VOUGA", model: "CK-6140S", deliveryDate: "2008-10-20" },
  { no: 19, firm: "ALİBEYKÖY E.M. LİSESİ", contact: "Mesut Hoca", district: "Alibeyköy", city: "İstanbul", brand: "VOUGA", model: "CK-6150S", deliveryDate: "2008-10-27" },
  { no: 20, firm: "AFYON ÇAY E.M.LİSESİ", contact: "Refik YILMAZ", district: "Çay", city: "Afyon", brand: "VOUGA", model: "CK-6140S", deliveryDate: "2008-10-31" },
  { no: 21, firm: "MUŞ ALPARSLAN ÜNİV.", contact: "", district: "Merkez", city: "Muş", brand: "VOUGA", model: "CK-6140S", deliveryDate: "2009-10-05" },
  { no: 22, firm: "KERVAN TEKSTİL", contact: "Abdullah BAŞPINAR", district: "Güngören", city: "İstanbul", brand: "LK MACHINERY", model: "TT-510P", deliveryDate: "2010-01-21" },
  { no: 23, firm: "KÖSE OTOMAT", contact: "İbrahim KÖSE", district: "Bayrampaşa", city: "İstanbul", brand: "LK MACHINERY", model: "TC-510", deliveryDate: "2010-07-29" },
  { no: 24, firm: "MAÇKA METAL", contact: "Ersin ÖZÇETİN", district: "Küçükçekmece", city: "İstanbul", brand: "MAXIMART", model: "V-6D", deliveryDate: "2010-10-20" },
  { no: 25, firm: "ÖZGE TORNA", contact: "Ercan KARTAL", district: "Pendik", city: "İstanbul", brand: "ECOCA", model: "SL-8P", deliveryDate: "2010-11-03" },
  { no: 26, firm: "ÇAKMAK KALIP", contact: "Turgut ÇAKMAK", district: "Başakşehir", city: "İstanbul", brand: "AGMA", model: "VMC-115", deliveryDate: "2010-11-04" },
  { no: 27, firm: "GENÇLER KALIP", contact: "Nevzat DEVECİOĞLU", district: "Bayrampaşa", city: "İstanbul", brand: "VOUGA", model: "SW DX5050", deliveryDate: "2010-11-09" },
  { no: 28, firm: "ÖZMAKSAN MEGAFÜZYON", contact: "Şahin ÖZDEMİR", district: "Ostim", city: "Ankara", brand: "ECOCA", model: "MT-310/750", deliveryDate: "2010-11-09" },
  { no: 29, firm: "KADIRGA END.MSL.LİSESİ", contact: "Şükrü ERSOY", district: "Fatih", city: "İstanbul", brand: "LK MACHINERY", model: "TT-510P", deliveryDate: "2010-12-01" },
  { no: 30, firm: "GENÇLER KALIP", contact: "Nevzat DEVECİOĞLU", district: "Bayrampaşa", city: "İstanbul", brand: "MAXIMART", model: "VMC-65S", deliveryDate: "2010-12-10" },
  { no: 31, firm: "ÖNSA ASANSÖR", contact: "Şevket ÖNER", district: "Başakşehir", city: "İstanbul", brand: "VOUGA", model: "CK 6140S", deliveryDate: "2010-12-14" },
  { no: 32, firm: "ÖNSA ASANSÖR", contact: "Şevket ÖNER", district: "Başakşehir", city: "İstanbul", brand: "MAXIMART", model: "BMC-5AS", deliveryDate: "2010-12-14" },
  { no: 33, firm: "GENERAL KALIP", contact: "Fatih ÖZATA", district: "Bayrampaşa", city: "İstanbul", brand: "MAXIMART", model: "V-11C", deliveryDate: "2011-01-13" },
  { no: 34, firm: "ZİRVE-BİR KALIP", contact: "Remzi SOYLU", district: "Pendik", city: "İstanbul", brand: "ARISTECH", model: "CW-50S", deliveryDate: "2011-01-15" },
  { no: 35, firm: "ÖZ-İŞ TORNA", contact: "Alper GÜRSOY", district: "Avcılar", city: "İstanbul", brand: "ECOCA", model: "SL-8P", deliveryDate: "2011-01-21" },
  { no: 36, firm: "BATMAN END.MSL.LİSESİ", contact: "Cemalettin AYDIN", district: "Merkez", city: "Batman", brand: "ECOCA", model: "SL-8P", deliveryDate: "2011-01-25" },
  { no: 37, firm: "GÜNTUĞ MAKİNA", contact: "Cevdet GÜNEY", district: "Gebze", city: "Kocaeli", brand: "ECOCA", model: "MT-208/500", deliveryDate: "2011-01-28" },
  { no: 38, firm: "TUZUN KALIP", contact: "Metin TUZUN", district: "Bayrampaşa", city: "İstanbul", brand: "LK MACHINERY", model: "TC-510", deliveryDate: "2011-02-01" },
  { no: 39, firm: "AKON KONİK", contact: "Veysel ÇÖKEK", district: "Başakşehir", city: "İstanbul", brand: "ECOCA", model: "MT-210/500", deliveryDate: "2011-02-20" },
  { no: 40, firm: "GÜNGÖRLER MAKİNA", contact: "Hüseyin GÜNGÖR", district: "Çan", city: "Çanakkale", brand: "VOUGA", model: "CK 6140S", deliveryDate: "2011-02-25" },
  { no: 41, firm: "AKON KONİK", contact: "Veysel ÇÖKEK", district: "Başakşehir", city: "İstanbul", brand: "LK MACHINERY", model: "TC-510", deliveryDate: "2011-03-07" },
  { no: 42, firm: "AYSANMAK MAKİNA", contact: "Halis ARIBAŞ", district: "Nilüfer", city: "Bursa", brand: "MAXIMART", model: "Q-13", deliveryDate: "2011-03-14" },
  { no: 43, firm: "ZİRVE-BİR KALIP", contact: "Remzi SOYLU", district: "Pendik", city: "İstanbul", brand: "MAXIMART", model: "V-11D", deliveryDate: "2011-03-18" },
  { no: 44, firm: "ÖZMAK TEKSTİL", contact: "Rıza ÖZTÜRK", district: "Başakşehir", city: "İstanbul", brand: "ECOCA", model: "MT-312/750", deliveryDate: "2011-03-21" },
  { no: 45, firm: "KADIRGA END.MSL.LİSESİ", contact: "Şükrü ERSOY", district: "Fatih", city: "İstanbul", brand: "VOUGA", model: "CK 6140S", deliveryDate: "2011-04-06" },
  { no: 46, firm: "VOLKAN MAKİNA", contact: "Hakan ENERSOY", district: "Bayrampaşa", city: "İstanbul", brand: "MAXIMART", model: "VMC-65S", deliveryDate: "2011-04-10" },
  { no: 47, firm: "ÖZKA DÖKÜM", contact: "Selim KALAYCI", district: "Başakşehir", city: "İstanbul", brand: "ECOCA", model: "MT-208/500", deliveryDate: "2011-04-14" },
  { no: 48, firm: "TEZELMAK MAKİNA", contact: "Eşref TEZEL", district: "G.O.Paşa", city: "İstanbul", brand: "MAXIMART", model: "VMC-105E", deliveryDate: "2011-04-22" },
  { no: 49, firm: "DİZAYN MODEL TASARIM", contact: "Bilal ÇATAK", district: "Bayrampaşa", city: "İstanbul", brand: "LK MACHINERY", model: "TC-510", deliveryDate: "2011-04-30" },
  { no: 50, firm: "ENSA MAKİNA", contact: "Mustafa BAYAR", district: "Küçükçekmece", city: "İstanbul", brand: "ECOCA", model: "MT-310/750", deliveryDate: "2011-04-30" },
  { no: 51, firm: "BİRSAN CAM KAPI", contact: "İbrahim AYDIN", district: "Bayrampaşa", city: "İstanbul", brand: "VOUGA", model: "CK 6150S", deliveryDate: "2011-04-30" },
  { no: 52, firm: "ROBUST OTOMASYON", contact: "Beysin UZUNOĞLU", district: "Başakşehir", city: "İstanbul", brand: "MAXIMART", model: "BMC-5AS", deliveryDate: "2011-05-06" },
  { no: 53, firm: "DOĞAN METAL", contact: "Mustafa DOĞAN", district: "Başakşehir", city: "İstanbul", brand: "ARISTECH", model: "DW-35", deliveryDate: "2011-05-20" },
  { no: 54, firm: "KOR METAL", contact: "Ozan DAL", district: "Avcılar", city: "İstanbul", brand: "LK MACHINERY", model: "TC-510", deliveryDate: "2011-05-30" },
  { no: 55, firm: "ZİRVE-BİR KALIP", contact: "Remzi SOYLU", district: "Pendik", city: "İstanbul", brand: "MAXIMART", model: "VMC-65S", deliveryDate: "2011-05-31" },
  { no: 56, firm: "FEMAŞ MAKİNA", contact: "Cihat AKKUŞ", district: "Merkez", city: "Aydın", brand: "ECOCA", model: "SL-8P", deliveryDate: "2011-06-03" },
  { no: 57, firm: "KAHYAOĞLU MAKİNA", contact: "Adnan KAHYAOĞLU", district: "Nazilli", city: "Aydın", brand: "VOUGA", model: "CK 6150S", deliveryDate: "2011-06-03" },
  { no: 58, firm: "SEGA MAKİNA", contact: "Seyyid GANİ", district: "Başakşehir", city: "İstanbul", brand: "LK MACHINERY", model: "TC-510", deliveryDate: "2011-06-07" },
  { no: 59, firm: "ÖZKA DÖKÜM", contact: "Selim KALAYCI", district: "Başakşehir", city: "İstanbul", brand: "ECOCA", model: "MT-208/500", deliveryDate: "2011-06-11" },
  { no: 60, firm: "HİLALSAN", contact: "Seyit Ali COPLAN", district: "Merkez", city: "Konya", brand: "ECOCA", model: "MT-208/500", deliveryDate: "2011-06-13" },
  { no: 61, firm: "DİSPA MAKİNA", contact: "Süleyman DABAN", district: "Nilüfer", city: "Bursa", brand: "ECOCA", model: "MT-210/750", deliveryDate: "2011-06-17" },
  { no: 62, firm: "BAŞARAN TORNA", contact: "Dursun SATIR", district: "Ostim", city: "Ankara", brand: "ECOCA", model: "SL-8P", deliveryDate: "2011-06-30" },
  { no: 63, firm: "YACOH MAKİNA", contact: "Yusuf ÖZDEMİR", district: "Topçular", city: "İstanbul", brand: "MAXIMART", model: "BMC-5 AS", deliveryDate: "2011-07-14" },
  { no: 64, firm: "PLAST-MET KALIP", contact: "Erol ŞENOL", district: "Sancaktepe", city: "İstanbul", brand: "ARISTECH", model: "CNC-650 C EKSEN", deliveryDate: "2011-07-29" },
  { no: 65, firm: "PLAST-MET KALIP", contact: "Erol ŞENOL", district: "Sancaktepe", city: "İstanbul", brand: "ARISTECH", model: "CNC-2010 ÇİFT KAFA", deliveryDate: "2011-07-29" },
  { no: 66, firm: "AKYAPAK MAKİNA", contact: "Leven AKYAPAK", district: "Akçalar", city: "Bursa", brand: "MAXIMART", model: "Q-13", deliveryDate: "2011-08-11" },
  { no: 67, firm: "ERDİNÇ MAKİNA", contact: "Mesut KUŞ", district: "Bayrampaşa", city: "İstanbul", brand: "LK MACHINERY", model: "TC-510", deliveryDate: "2011-09-20" },
  { no: 68, firm: "ÖZ-İŞ TORNA", contact: "Alper GÜRSOY", district: "Avcılar", city: "İstanbul", brand: "ECOCA", model: "MT-412/1500", deliveryDate: "2011-09-25" },
  { no: 69, firm: "ÖNSA ASANSÖR", contact: "Şevket ÖNER", district: "Başakşehir", city: "İstanbul", brand: "HOYATECH", model: "TC-25", deliveryDate: "2011-11-11" },
  { no: 70, firm: "TEKSAN CAM KAPI", contact: "Ömer ÖMEROĞLU", district: "Bayrampaşa", city: "İstanbul", brand: "VOUGA", model: "CK 6140S", deliveryDate: "2011-11-12" },
  { no: 71, firm: "TEKSAN CAM KAPI", contact: "Ömer ÖMEROĞLU", district: "Bayrampaşa", city: "İstanbul", brand: "VOUGA", model: "CK 6140S", deliveryDate: "2011-11-12" },
  { no: 72, firm: "AKTEK TEKNOLOHİ MÜH.", contact: "İrfan AKGÜN", district: "Gölcük", city: "Kocaeli", brand: "MAXIMART", model: "BMC-7AS", deliveryDate: "2012-01-04" },
  { no: 73, firm: "ZİRVE-BİR KALIP", contact: "Remzi SOYLU", district: "Pendik", city: "İstanbul", brand: "MAXIMART", model: "V-11D", deliveryDate: "2012-05-01" },
  { no: 74, firm: "AR MAKİNA KALIP", contact: "Recep YILDIRIM", district: "Başakşehir", city: "İstanbul", brand: "LK MACHINERY", model: "MV-850", deliveryDate: "2012-05-01" },
  { no: 75, firm: "ASLANLAR KALIP", contact: "Cebbar AVCI", district: "Seyhan", city: "Adana", brand: "ECOCA", model: "MT-310/750", deliveryDate: "2012-07-09" },
  { no: 76, firm: "EREN ÇELİK AHŞAP", contact: "Kemal EREN", district: "Dilovası", city: "Kocaeli", brand: "LK MACHINERY", model: "MV-1050", deliveryDate: "2012-11-07" },
  { no: 77, firm: "İMPOL POLİÜRETAN", contact: "İmdat KOCABAŞ", district: "Yıldırım", city: "Bursa", brand: "VOUGA", model: "CK-6156", deliveryDate: "2012-11-16" },
  { no: 78, firm: "KÜRSAN MAKİNA", contact: "Ali KÜREKÇİ", district: "Erbil", city: "Irak", brand: "VOUGA", model: "CK-6140S", deliveryDate: "2012-11-24" },
  { no: 79, firm: "CİBO METAL", contact: "Murat CİBO", district: "Pendik", city: "İstanbul", brand: "LK MACHINERY", model: "MV-650", deliveryDate: "2012-12-12" },
  { no: 80, firm: "TUĞRA MAKİNA", contact: "Nihat BAŞAK", district: "Başakşehir", city: "İstanbul", brand: "LK MACHINERY", model: "TC-510", deliveryDate: "2013-01-25" },
  { no: 81, firm: "ÖZKUR MAKİNA", contact: "Ahmet ÖZER", district: "Osmangazi", city: "Bursa", brand: "CHEVALLIER (K)", model: "VMC-2443", deliveryDate: "2013-02-01" },
  { no: 82, firm: "ISITAN MAKİNA", contact: "Serkan ŞAHİN", district: "Nilüfer", city: "Bursa", brand: "LK MACHINERY", model: "TC-510", deliveryDate: "2013-03-04" },
  { no: 83, firm: "AKTEK TEKNOLOHİ MÜH.", contact: "İrfan AKGÜN", district: "Gölcük", city: "Kocaeli", brand: "LK MACHINERY", model: "TC-710", deliveryDate: "2013-03-04" },
  { no: 84, firm: "GÜRKAN MAKİNA", contact: "Muzaffer GÜRKAN", district: "Başakşehir", city: "İstanbul", brand: "HAXAN (ECOCA)", model: "HX-08A (MT-208)", deliveryDate: "2013-04-01" },
  { no: 85, firm: "ALPEREN OTOMOTİV", contact: "Mustafa KESEN", district: "Beylikdüzü", city: "İstanbul", brand: "LK MACHINERY", model: "TC-510", deliveryDate: "2013-04-07" },
  { no: 86, firm: "PAKİŞ CNC", contact: "Enes HÜLAGU", district: "Bayrampaşa", city: "İstanbul", brand: "LK MACHINERY", model: "MV-1050", deliveryDate: "2013-05-04" },
  { no: 87, firm: "KÖSE OTOMAT", contact: "İbrahim KÖSE", district: "Bayrampaşa", city: "İstanbul", brand: "LK MACHINERY", model: "MV-850", deliveryDate: "2013-05-06" },
  { no: 88, firm: "AKTEK TEKNOLOHİ MÜH.", contact: "İrfan AKGÜN", district: "Gölcük", city: "Kocaeli", brand: "LK MACHINERY", model: "TT-510P", deliveryDate: "2013-05-09" },
  { no: 89, firm: "ÖNSA ASANSÖR", contact: "Şevket ÖNER", district: "Başakşehir", city: "İstanbul", brand: "HAXAN (ECOCA)", model: "HX-10B (MT-310)", deliveryDate: "2013-05-15" },
  { no: 90, firm: "KERVAN TEKSTİL", contact: "Ahmet YILMAZ", district: "Yenibosna", city: "İstanbul", brand: "LK MACHINERY", model: "MV-850", deliveryDate: "2013-09-10" },
  { no: 91, firm: "KERVAN TEKSTİL", contact: "Ahmet YILMAZ", district: "Yenibosna", city: "İstanbul", brand: "ARISTECH", model: "DW-35", deliveryDate: "2013-09-10" },
  { no: 92, firm: "TEKSAN CAM KAPI", contact: "Ömer ÖMEROĞLU", district: "Bayrampaşa", city: "İstanbul", brand: "LK MACHINERY", model: "MV-850", deliveryDate: "2013-09-24" },
  { no: 93, firm: "KERVAN TEKSTİL", contact: "Ahmet YILMAZ", district: "Yenibosna", city: "İstanbul", brand: "LK MACHINERY", model: "TT-510P", deliveryDate: "2013-09-20" },
  { no: 94, firm: "LEBRETAH INDUSTRIAL", contact: "Basel MOUNDANI", district: "Şam", city: "Suriye", brand: "HAXAN (ECOCA)", model: "HX-10B (MT-310)", deliveryDate: "2013-09-27" },
  { no: 95, firm: "LEBRETAH INDUSTRIAL", contact: "Basel MOUNDANI", district: "Şam", city: "Suriye", brand: "HAXAN (ECOCA)", model: "HX-08A (MT-208)", deliveryDate: "2013-09-28" },
  { no: 96, firm: "ZİRVE-BİR KALIP", contact: "Remzi SOYLU", district: "Pendik", city: "İstanbul", brand: "MAXIMART", model: "V-6H", deliveryDate: "2013-10-07" },
  { no: 97, firm: "ERAL MAKİNA", contact: "Ayhan VELİOĞLU", district: "Esenyurt", city: "İstanbul", brand: "HAXAN (ECOCA)", model: "HX-12F (MT-412)", deliveryDate: "2013-10-09" },
  { no: 98, firm: "SAVEMA MAKİNA", contact: "Mustafa SAĞBİLİ", district: "Karatay", city: "Konya", brand: "LK MACHINERY", model: "TC-510", deliveryDate: "2013-10-11" },
  { no: 99, firm: "ZİRVE-BİR KALIP", contact: "Remzi SOYLU", district: "Pendik", city: "İstanbul", brand: "LK MACHINERY", model: "MV-650", deliveryDate: "2013-10-18" },
  { no: 100, firm: "BORSAN CNC", contact: "Fatih KARAKALE", district: "Bayrampaşa", city: "İstanbul", brand: "HAXAN (ECOCA)", model: "HL-8 (SL-8P)", deliveryDate: "2013-12-10" },
  { no: 101, firm: "YK KALIP", contact: "Servet YILMAZ", district: "Bayrampaşa", city: "İstanbul", brand: "LK MACHINERY", model: "TC-510", deliveryDate: "2013-12-14" },
  { no: 102, firm: "YK KALIP", contact: "Servet YILMAZ", district: "Bayrampaşa", city: "İstanbul", brand: "LK MACHINERY", model: "TC-510", deliveryDate: "2013-12-16" },
  { no: 103, firm: "ÇAĞLAK MAKİNA", contact: "Kenan ÇAĞLAK", district: "Merkez", city: "Çorum", brand: "HAXAN (ECOCA)", model: "HX-08A (MT-208)", deliveryDate: "2013-12-19" },
  { no: 104, firm: "FEMAŞ MAKİNA", contact: "Cihat AKKUŞ", district: "Merkez", city: "Aydın", brand: "LK MACHINERY", model: "MV-850", deliveryDate: "2013-12-25" },
  { no: 105, firm: "İNTEGROS MEDİKAL", contact: "Harun GARGIN", district: "İkitelli", city: "İstanbul", brand: "VOUGA", model: "CK-6140S", deliveryDate: "2014-04-11" },
  { no: 106, firm: "İNTEGROS MEDİKAL", contact: "Harun GARGIN", district: "İkitelli", city: "İstanbul", brand: "LK MACHINERY", model: "MV-1050", deliveryDate: "2014-04-15" },
  { no: 107, firm: "SOMA END. MSL. LİSESİ", contact: "Bayi (Borsan)", district: "Soma", city: "Manisa", brand: "ECOCA", model: "SL-8P", deliveryDate: "2014-04-18" },
  { no: 108, firm: "EDİRNE MSL. YÜK. OKULU", contact: "Bayi (Borsan)", district: "Sarayiçi", city: "Edirne", brand: "VOUGA", model: "CK-6140S", deliveryDate: "2014-04-18" },
  { no: 109, firm: "HEKSİMPLANT", contact: "Mehmet HAFIZOĞLU", district: "İkitelli", city: "İstanbul", brand: "LK MACHINERY", model: "TC-510", deliveryDate: "2014-05-08" },
  { no: 110, firm: "KÖSE OTOMAT", contact: "İbrahim KÖSE", district: "Bayrampaşa", city: "İstanbul", brand: "ECOCA", model: "MT-310/750", deliveryDate: "2014-05-15" },
  { no: 111, firm: "ÖZ-İŞ TORNA TESVİYE", contact: "Erdinç GÜRSOY", district: "Çerkezköy", city: "Tekirdağ", brand: "ECOCA", model: "SL-8", deliveryDate: "2014-05-27" },
  { no: 112, firm: "PAKİŞ CNC", contact: "Enes HÜLAGU", district: "Bayrampaşa", city: "İstanbul", brand: "LK MACHINERY", model: "MV-650", deliveryDate: "2014-06-10" },
  { no: 113, firm: "CEMAX MAKİNA", contact: "Cem ARICI", district: "Yeni Mahalle", city: "Ankara", brand: "LK MACHINERY", model: "MV-1050", deliveryDate: "2014-07-10" },
  { no: 114, firm: "ÇELMAK MAKİNA", contact: "Halis ÇELİK", district: "Fırat Teknokent", city: "Elazığ", brand: "VOUGA", model: "CK-6140S", deliveryDate: "2014-09-14" },
  { no: 115, firm: "ARAN MAKİNA", contact: "Mustafa ARMUTÇUOĞLU", district: "Bayrampaşa", city: "İstanbul", brand: "ECOCA", model: "SL-8", deliveryDate: "2014-09-26" },
  { no: 116, firm: "EREN TEKNİK OTOMOTİV", contact: "Mehmet BULUT", district: "İkitelli", city: "İstanbul", brand: "ECOCA", model: "MT-208/500", deliveryDate: "2014-09-29" },
  { no: 117, firm: "EREN TEKNİK OTOMOTİV", contact: "Mehmet BULUT", district: "İkitelli", city: "İstanbul", brand: "LK MACHINERY", model: "MV-850", deliveryDate: "2014-09-29" },
  { no: 118, firm: "TEKMAK TORNA", contact: "İlker SARITAŞ", district: "İkitelli", city: "İstanbul", brand: "VOUGA", model: "CK-6156/2000", deliveryDate: "2014-10-17" },
  { no: 119, firm: "DİSPA MAKİNA", contact: "Süleyman DABAN", district: "Nilüfer", city: "Bursa", brand: "LK MACHINERY", model: "MV-1050", deliveryDate: "2014-11-11" },
  { no: 120, firm: "HAKFORM CNC", contact: "Halil İbrahim BAŞAK", district: "Bayrampaşa", city: "İstanbul", brand: "LK MACHINERY", model: "MV-1050", deliveryDate: "2014-11-20" },
  { no: 121, firm: "NURPET MAKİNA", contact: "Adnan MERİÇ", district: "Beylikdüzü", city: "İstanbul", brand: "LK MACHINERY", model: "MV-1050", deliveryDate: "2014-11-22" },
  { no: 122, firm: "BERGAMA END.MSL.LİS.", contact: "Bayi (Borsan)", district: "Bergama", city: "İzmir", brand: "LK MACHINERY", model: "TC-510", deliveryDate: "2014-12-08" },
  { no: 123, firm: "ÖNÇIRAK MAKİNA", contact: "Ahmet ÖNÇIRAK", district: "Ardeşen", city: "Rize", brand: "LK MACHINERY", model: "TC-710", deliveryDate: "2014-12-12" },
  { no: 124, firm: "NETPAK AMBALAJ", contact: "Ali AVCI", district: "Bayrampaşa", city: "İstanbul", brand: "LK MACHINERY", model: "MV-850", deliveryDate: "2014-12-26" },
  { no: 125, firm: "OBJE PLASTİK", contact: "Sami AKKAYA", district: "Bayrampaşa", city: "İstanbul", brand: "BAYKAL", model: "BF-70200", deliveryDate: "2014-12-29" },
  { no: 126, firm: "HOBİ EGZOST", contact: "Ahmet MORGÜL", district: "Silivri", city: "İstanbul", brand: "ECOCA", model: "MT-208/500", deliveryDate: "2015-01-05" },
  { no: 127, firm: "MAKENA MÜHENDİSLİK", contact: "Erol GÜNAYDIN", district: "Bayrampaşa", city: "İstanbul", brand: "LK MACHINERY", model: "TC-510", deliveryDate: "2015-01-11" },
  { no: 128, firm: "NERO SAVUNMA", contact: "Alican OKÇUN", district: "İkitelli", city: "İstanbul", brand: "ECOCA", model: "SL-8", deliveryDate: "2015-01-17" },
  { no: 129, firm: "KURTOĞLU BAKIR", contact: "Cengiz SERTEL", district: "Velimeşe", city: "Tekirdağ", brand: "LK MACHINERY", model: "TC-510", deliveryDate: "2015-01-23" },
  { no: 130, firm: "ORTA TORNA", contact: "Ahmet ORTA", district: "Çorlu", city: "Tekirdağ", brand: "ECOCA", model: "MT-310/750", deliveryDate: "2015-02-24" },
  { no: 131, firm: "ÖNSA ASANSÖR", contact: "Şevket ÖNER", district: "Başakşehir", city: "İstanbul", brand: "ECOCA", model: "SL-8", deliveryDate: "2015-03-10" },
  { no: 132, firm: "EGE CONTA", contact: "Mukadder EGELİ", district: "Bayrampaşa", city: "İstanbul", brand: "LK MACHINERY", model: "MV-650", deliveryDate: "2015-04-10" },
  { no: 133, firm: "FACTORH OTOMASYON", contact: "Vural HAKYEMEZ", district: "Seyrantepe", city: "İstanbul", brand: "LK MACHINERY", model: "MV-1050", deliveryDate: "2015-04-18" },
  { no: 134, firm: "MERCAN MODEL", contact: "Hakkı MERCAN", district: "Bayrampaşa", city: "İstanbul", brand: "LK MACHINERY", model: "TC-510", deliveryDate: "2015-04-27" },
  { no: 135, firm: "BTS MAKİNA", contact: "Bülent TURGUT", district: "Nilüfer", city: "Bursa", brand: "LK MACHINERY", model: "MV-1050", deliveryDate: "2015-05-05" },
  { no: 136, firm: "ŞAHİNLER FORM METAL", contact: "Nazmi KIRIMCI", district: "Kayapa", city: "Bursa", brand: "LK MACHINERY", model: "MV-850", deliveryDate: "2015-05-05" },
  { no: 137, firm: "MİKRON MAKİNA", contact: "Nadir ÖZDEMİR", district: "Sakarya", city: "Adapazarı", brand: "LK MACHINERY", model: "MV-850", deliveryDate: "2015-05-05" },
  { no: 138, firm: "ALOMARY TECH.", contact: "Tammam Alrewdhs", district: "Halep", city: "Suriye", brand: "VOUGA", model: "CK-6156B", deliveryDate: "2015-06-03" },
  { no: 139, firm: "NERO SAVUNMA", contact: "Dinçer Oğuz", district: "İkitelli", city: "İstanbul", brand: "LK MACHINERY", model: "TC-510", deliveryDate: "2015-06-28" },
  { no: 140, firm: "ISITAN MAKİNA", contact: "Serkan ŞAHİN", district: "Nilüfer", city: "Bursa", brand: "ECOCA", model: "MT-412/1500", deliveryDate: "2015-07-21" },
  { no: 141, firm: "KESKİNLER KALIP", contact: "Hüseyin KESKİN", district: "Pendik", city: "İstanbul", brand: "LK MACHINERY", model: "MV-850", deliveryDate: "2015-07-22" },
  { no: 142, firm: "SEYİR MÜHENDİSLİK", contact: "Erkan SANDIKÇI", district: "Erenler", city: "Adapazarı", brand: "ECOCA", model: "MT-310/750", deliveryDate: "2015-08-11" },
  { no: 143, firm: "DİZAYN MAKİNA", contact: "Necmettin ÖZTÜRK", district: "Bayrampaşa", city: "İstanbul", brand: "ECOCA", model: "SL-8", deliveryDate: "2015-09-30" },
  { no: 144, firm: "HOBİ EGZOST", contact: "Ahmet MORGÜL", district: "Silivri", city: "İstanbul", brand: "ECOCA", model: "MT-208/500", deliveryDate: "2015-10-08" },
  { no: 145, firm: "CESUR BEND", contact: "Turan CESUR", district: "Nilüfer", city: "Bursa", brand: "LK MACHINERY", model: "MV-1050", deliveryDate: "2015-10-21" },
  { no: 146, firm: "ELAZIĞ END. MSL. LİSESİ", contact: "Bayi (Borsan)", district: "Merkez", city: "Elazığ", brand: "VOUGA", model: "CK-6140S", deliveryDate: "2015-11-14" },
  { no: 147, firm: "SNS KALIP MAKİNA", contact: "Selçuk KILIÇ", district: "Bayrampaşa", city: "İstanbul", brand: "LK MACHINERY", model: "MV-650", deliveryDate: "2015-11-20" },
  { no: 148, firm: "EREN TEKNİK OTOMOTİV", contact: "Mehmet BULUT", district: "İkitelli", city: "İstanbul", brand: "LK MACHINERY", model: "MV-850", deliveryDate: "2015-12-03" },
  { no: 149, firm: "DEVLET SU İŞLERİ", contact: "Bayi (Borsan)", district: "Merkez", city: "Ankara", brand: "ECOCA", model: "MT-310/500 MC", deliveryDate: "2015-12-10" },
  { no: 150, firm: "ACROME", contact: "Ercüment Öztürk", district: "İkitelli", city: "İstanbul", brand: "YUNNAN", model: "CY-K360n", deliveryDate: "2015-12-25" },
  { no: 151, firm: "YK KALIP", contact: "Servet YILMAZ", district: "Bayrampaşa", city: "İstanbul", brand: "LK MACHINERY", model: "MV-850", deliveryDate: "2015-12-26" },
  { no: 152, firm: "CESUR BEND", contact: "Turan CESUR", district: "Nilüfer", city: "Bursa", brand: "ECOCA", model: "MT-310/750", deliveryDate: "2016-01-14" },
  { no: 153, firm: "PLASTKOM PLASTİK", contact: "Ufuk AYDIN", district: "Tuzla", city: "İstanbul", brand: "ECOCA", model: "MT-208/500", deliveryDate: "2016-01-19" },
  { no: 154, firm: "PLASTKOM PLASTİK", contact: "Ufuk AYDIN", district: "Tuzla", city: "İstanbul", brand: "LK MACHINERY", model: "MV-1050", deliveryDate: "2016-01-19" },
  { no: 155, firm: "ÖZGEN PLASTİK", contact: "Yusuf YAPICI", district: "Bayrampaşa", city: "İstanbul", brand: "LK MACHINERY", model: "MV-850", deliveryDate: "2016-02-13" },
  { no: 156, firm: "MERCAN MODEL", contact: "Hakkı MERCAN", district: "Bayrampaşa", city: "İstanbul", brand: "LK MACHINERY", model: "TC-510", deliveryDate: "2016-02-13" },
  { no: 157, firm: "RAVZA MAKİNA", contact: "İdris AYDIN", district: "Bayrampaşa", city: "İstanbul", brand: "LK MACHINERY", model: "MV-1050", deliveryDate: "2016-02-19" },
  { no: 158, firm: "FARS AFZAR KİMYA CO.", contact: "Saied ERJAEE", district: "Shiraz", city: "İhracat", brand: "ECOCA", model: "SL-8", deliveryDate: "2016-03-11" },
  { no: 159, firm: "FARS AFZAR KİMYA CO.", contact: "Saied ERJAEE", district: "Shiraz", city: "İran", brand: "ECOCA", model: "MT-310/750", deliveryDate: "2016-03-11" },
  { no: 160, firm: "YK KALIP", contact: "Servet YILMAZ", district: "Bayrampaşa", city: "İstanbul", brand: "LK MACHINERY", model: "MV-850", deliveryDate: "2016-04-28" },
  { no: 161, firm: "APEKS APARAT", contact: "Rıdvan DESTEK", district: "Yenibosna", city: "İstanbul", brand: "LK MACHINERY", model: "TC-510", deliveryDate: "2016-06-08" },
  { no: 162, firm: "ZARIF AFZAR ENGINEERING", contact: "Aziz ASADOLLAH", district: "Shiraz", city: "İran", brand: "ECOCA", model: "MT-310/750", deliveryDate: "2016-06-17" },
  { no: 163, firm: "ZARIF AFZAR ENGINEERING", contact: "Aziz ASADOLLAH", district: "Shiraz", city: "İran", brand: "ECOCA", model: "MT-208/750", deliveryDate: "2016-06-17" },
  { no: 164, firm: "KESKİNLER KALIP", contact: "Hüseyin KESKİN", district: "Pendik", city: "İstanbul", brand: "ECOCA", model: "VB-1200", deliveryDate: "2016-07-01" },
  { no: 165, firm: "TALHA MODEL", contact: "Servkan VURAL", district: "Bayrampaşa", city: "İstanbul", brand: "LK MACHINERY", model: "TC-510", deliveryDate: "2016-07-16" },
  { no: 166, firm: "BALIKLI KALIP", contact: "Mehmet KOCABAL", district: "Bayrampaşa", city: "İstanbul", brand: "ECOCA", model: "VL-800", deliveryDate: "2016-08-25" },
  { no: 167, firm: "DİZAYN MAKİNA", contact: "Necmettin ÖZTÜRK", district: "İkitelli", city: "İstanbul", brand: "ECOCA", model: "MT 310/750", deliveryDate: "2016-08-26" },
  { no: 168, firm: "DİZAYN MAKİNA", contact: "Necmettin ÖZTÜRK", district: "İkitelli", city: "İstanbul", brand: "LK MACHINERY", model: "MV-1050", deliveryDate: "2016-10-04" },
  { no: 169, firm: "MASAM MAKİNA", contact: "Necati ÖZTÜRK", district: "Pendik", city: "İstanbul", brand: "ECOCA", model: "VB-1600", deliveryDate: "2016-10-18" },
  { no: 170, firm: "DAŞKAR MAKİNA", contact: "Ahmet AKGÖĞ", district: "Yıldırım", city: "Bursa", brand: "ECOCA", model: "MT-310/500L", deliveryDate: "2016-11-03" },
  { no: 171, firm: "ASLIM KALIP", contact: "Çiğdem ASLIM", district: "Nilüfer", city: "Bursa", brand: "LK MACHINERY", model: "MV-1050", deliveryDate: "2016-11-23" },
  { no: 172, firm: "FARS AFZAR KİMYA CO.", contact: "Aziz ASADOLLAH", district: "Shiraz", city: "İran", brand: "ECOCA", model: "SJ-20", deliveryDate: "2016-11-25" },
  { no: 173, firm: "FARS AFZAR KİMYA CO.", contact: "Aziz ASADOLLAH", district: "Shiraz", city: "İran", brand: "ECOCA", model: "SC-20", deliveryDate: "2016-11-25" },
  { no: 174, firm: "İLTAŞ METAL", contact: "İlyas TABAN", district: "Nilüfer", city: "Bursa", brand: "ECOCA", model: "SL-8", deliveryDate: "2016-12-24" },
  { no: 175, firm: "AKBAŞLAR MAKİNA", contact: "Haluk AKBAŞ", district: "Başakşehir", city: "İstanbul", brand: "ECOCA", model: "MT-310/500L", deliveryDate: "2017-02-22" },
  { no: 176, firm: "TEZELMAK MAKİNA", contact: "Eşref TEZEL", district: "Başakşehir", city: "İstanbul", brand: "LK MACHINERY", model: "MV-1050", deliveryDate: "2017-03-01" },
  { no: 177, firm: "ERSE TASARIM", contact: "Erhan TEMEL", district: "Bayrampaşa", city: "İstanbul", brand: "LK MACHINERY", model: "MV-850", deliveryDate: "2017-03-06" },
  { no: 178, firm: "HAKFORM CNC", contact: "Halil İbrahim BAŞAK", district: "Bayrampaşa", city: "İstanbul", brand: "LK MACHINERY", model: "MV-650", deliveryDate: "2017-03-13" },
  { no: 179, firm: "BURNET MAKİNA", contact: "Tarık DOĞRU", district: "Nilüfer", city: "Bursa", brand: "ECOCA", model: "MT-208/500", deliveryDate: "2017-04-26" },
  { no: 180, firm: "ÇAĞLAK MAKİNA", contact: "Kenan ÇAĞLAK", district: "Merkez", city: "Çorum", brand: "ECOCA", model: "SJ-20", deliveryDate: "2017-05-06" },
  { no: 181, firm: "BİZİM TEKNİK", contact: "Güven KAYAN", district: "Başakşehir", city: "İstanbul", brand: "ECOCA", model: "MT-312/500", deliveryDate: "2017-05-19" },
  { no: 182, firm: "ERKAN OTO YEDEK", contact: "Erkan HEPŞEN", district: "Başakşehir", city: "İstanbul", brand: "ECOCA", model: "SL-8", deliveryDate: "2017-07-03" },
  { no: 183, firm: "KILIÇ KALIP", contact: "Burhan KILIÇ", district: "Bayrampaşa", city: "İstanbul", brand: "ECOCA", model: "VL-800", deliveryDate: "2017-07-19" },
  { no: 184, firm: "KURTOĞLU BAKIR", contact: "Bülent ŞAHİN", district: "Çorlu", city: "Tekirdağ", brand: "LK MACHINERY", model: "TC-1200", deliveryDate: "2017-08-01" },
  { no: 185, firm: "ROLLTÜRK MAKİNA", contact: "Musa GERGİN", district: "Sancaktepe", city: "İstanbul", brand: "ECOCA", model: "MT-208/500", deliveryDate: "2017-08-09" },
  { no: 186, firm: "UMAY TASARIM", contact: "Cihangir BATMAZ", district: "Bayrampaşa", city: "İstanbul", brand: "LK MACHINERY", model: "MV-850", deliveryDate: "2017-08-10" },
  { no: 187, firm: "ELZEM MEDİKAL", contact: "Üzeyir ÇALIŞKAN", district: "Bornova", city: "İzmir", brand: "LK MACHINERY", model: "MV-1050", deliveryDate: "2017-08-23" },
  { no: 188, firm: "GÜVEN MAKİNA", contact: "Yusuf GÜVEN", district: "Bornova", city: "İzmir", brand: "LK MACHINERY", model: "VM-2", deliveryDate: "2017-08-24" },
  { no: 189, firm: "MERCAN SAVUNMA", contact: "Şuayib MERCAN", district: "Bayrampaşa", city: "İstanbul", brand: "COGENTECH", model: "CEM-650", deliveryDate: "2017-09-13" },
  { no: 190, firm: "ÇAĞAN MAKİNA", contact: "Emra ÇALDEMİR", district: "İkitelli", city: "İstanbul", brand: "ECOCA", model: "SL-8", deliveryDate: "2017-09-15" },
  { no: 191, firm: "ERDİNÇ MAKİNA", contact: "Mesut KUŞ", district: "Zeytinburnu", city: "İstanbul", brand: "LK MACHINERY", model: "TC-510", deliveryDate: "2017-09-19" },
  { no: 192, firm: "HANTEK KALIP", contact: "Galip BEĞEN", district: "Sultanbeyli", city: "İstanbul", brand: "LK MACHINERY", model: "MV-1050", deliveryDate: "2017-10-06" },
  { no: 193, firm: "ÜÇ-ER ELEKTRİK", contact: "Kenan ABALI", district: "Kağıthane", city: "İstanbul", brand: "LK MACHINERY", model: "MV-850", deliveryDate: "2017-10-06" },
  { no: 194, firm: "ELZEM MEDİKAL", contact: "Üzeyir ÇALIŞKAN", district: "Bornova", city: "İzmir", brand: "LK MACHINERY", model: "VM-2", deliveryDate: "2017-10-17" },
  { no: 195, firm: "ASYALI CNC", contact: "Ersin TAŞDEMİR", district: "Bayrampaşa", city: "İstanbul", brand: "ECOCA", model: "MT-208/500", deliveryDate: "2017-10-19" },
  { no: 196, firm: "CEMAX MAKİNA", contact: "Cem ARICI", district: "Yeni Mahalle", city: "Ankara", brand: "ECOCA", model: "MT-310/750", deliveryDate: "2017-11-08" },
  { no: 197, firm: "CEMAX MAKİNA", contact: "Cem ARICI", district: "Yeni Mahalle", city: "Ankara", brand: "LK MACHINERY", model: "MV-1050", deliveryDate: "2017-11-08" },
  { no: 198, firm: "PUSULA KALIP", contact: "Gökhan TÜZEN", district: "Bayrampaşa", city: "İstanbul", brand: "LK MACHINERY", model: "VM-2", deliveryDate: "2017-11-11" },
  { no: 199, firm: "YÜKSELİŞ ASANSÖR", contact: "Soner TEPE", district: "Kahramankazan", city: "Ankara", brand: "LK MACHINERY", model: "MV-1050", deliveryDate: "2017-12-01" },
  { no: 200, firm: "ULUÖZ KALIP", contact: "Cem ÖZKAYNAK", district: "Nilüfer", city: "Bursa", brand: "LK MACHINERY", model: "MV-1050", deliveryDate: "2018-01-04" },
];
