// Transcribed from AORE_Teknik_Parametreler_Turkce(1).xlsx; model columns, merged cells and source coordinates preserved.
// English/Chinese label aliases: AORE Technical Parameters.xlsx.
export const AORE_WORKBOOK_SHEETS = [
  {
    "name": "Standart Yapılandırma",
    "rows": [
      [
        "———— Yurt Dışı Ekipman Konfigürasyon Açıklama Tablosu 2025.03.18 ————",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Seri",
        "F",
        "FT",
        "GR-Pro",
        "PG",
        "PGT",
        "H",
        "FB",
        "PB",
        "R",
        "S",
        "TA",
        "TG",
        "TH",
        "TS",
        "TE",
        "TZ"
      ],
      [
        "Servo motor",
        "YASKAWA",
        "YASKAWA",
        "YASKAWA",
        "YASKAWA",
        "YASKAWA",
        "İtalya MOTOR POWER",
        "YASKAWA",
        "YASKAWA",
        "YASKAWA",
        "YASKAWA",
        "Çin INOVANCE",
        "Çin INOVANCE",
        "Çin INOVANCE",
        "Çin INOVANCE",
        "Çin INOVANCE",
        "Çin INOVANCE"
      ],
      [
        "Lineer kızak",
        "AORE standart konfigürasyonu",
        "AORE standart konfigürasyonu",
        "AORE standart konfigürasyonu",
        "AORE standart konfigürasyonu",
        "AORE standart konfigürasyonu",
        "Almanya Rexroth",
        "AORE standart konfigürasyonu",
        "AORE standart konfigürasyonu",
        "AORE standart konfigürasyonu",
        "AORE standart konfigürasyonu",
        "AORE standart konfigürasyonu",
        "AORE standart konfigürasyonu",
        "AORE standart konfigürasyonu",
        "AORE standart konfigürasyonu",
        "AORE standart konfigürasyonu",
        "AORE standart konfigürasyonu"
      ],
      [
        "Kremayer",
        "AORE standart konfigürasyonu",
        "AORE standart konfigürasyonu",
        "AORE standart konfigürasyonu",
        "AORE standart konfigürasyonu",
        "AORE standart konfigürasyonu",
        "Tayvan YYC",
        "AORE standart konfigürasyonu",
        "AORE standart konfigürasyonu",
        "AORE standart konfigürasyonu",
        "AORE standart konfigürasyonu",
        "AORE standart konfigürasyonu",
        "AORE standart konfigürasyonu",
        "AORE standart konfigürasyonu",
        "AORE standart konfigürasyonu",
        "AORE standart konfigürasyonu",
        "AORE standart konfigürasyonu"
      ],
      [
        "Redüktör",
        "KOFON",
        "KOFON",
        "KOFON",
        "KOFON",
        "KOFON",
        "Almanya Neugart\nNeugart",
        "KOFON",
        "KOFON",
        "KOFON",
        "KOFON",
        "KOFON\nK0FON",
        "KOFON",
        "KOFON",
        "KOFON",
        "KOFON",
        "KOFON"
      ],
      [
        "Su soğutucu",
        "HANLI",
        "HANLI",
        "HANLI",
        "HANLI",
        "HANLI",
        "HANLI",
        "HANLI",
        "HANLI",
        "HANLI",
        "HANLI",
        "HANLI",
        "HANLI",
        "HANLI",
        "HANLI",
        "HANLI",
        "HANLI"
      ],
      [
        "Elektrik bileşenleri",
        "CHNT/Omron\nCHNT/OMROM",
        "CHNT/Omron\nCHNT/OMROM",
        "Schneider/Omron\nSCHNEIDER/OMROM",
        "Schneider/Omron\nSCHNEIDER/OMROM",
        "Schneider/Omron\nSCHNEIDER/OMROM",
        "Schneider/Omron\nSCHNEIDER/OMROM",
        "Schneider/Omron\nSCHNEIDER/OMROM",
        "Schneider/Omron\nSCHNEIDER/OMROM",
        "Schneider/Omron\nSCHNEIDER/OMROM",
        "Schneider/Omron\nSCHNEIDER/OMROM",
        "Schneider/Omron\nSCHNEIDER/OMROM",
        "Schneider/Omron\nSCHNEIDER/OMROM",
        "Schneider/Omron\nSCHNEIDER/OMROM",
        "Schneider/Omron\nSCHNEIDER/OMROM",
        "Schneider/Omron\nSCHNEIDER/OMROM",
        "Schneider/Omron\nSCHNEIDER/OMROM"
      ],
      [
        "Oransal valf",
        "Japonya SMC",
        "Japonya SMC",
        "Japonya SMC",
        "Japonya SMC",
        "Japonya SMC",
        "Japonya SMC",
        "Japonya SMC",
        "Japonya SMC",
        "Japonya SMC",
        "Japonya SMC",
        "Japonya SMC",
        "Japonya SMC",
        "Japonya SMC",
        "Japonya SMC",
        "Japonya SMC",
        "Japonya SMC"
      ],
      [
        "Kontrol sistemi",
        "3kw:FSCUT2000E\n6kw :FSCUT4000E\n≥12kw:FSCUT8000",
        "≤6kw: FSCUT3000DE-M\n≥12kw:FSCUT5000B-H",
        "6kw:FSCUT4000E\n≥12kw:FSCUT8000",
        "≤3kw:FSCUT2000E\n6kw :FSCUT4000E\n≥12kw:FSCUT8000",
        "≤6kw: FSCUT3000DE-M\n≥12kw:FSCUT5000B-H",
        "BOCHU\nFSCUT8000A",
        "BOCHU\nFSCUT9100",
        "BOCHU\nFSCUT9100",
        "≤3kw:FSCUT2000E\n6kw :FSCUT4000E",
        "≤3kw:FSCUT2000E\n6kw:FSCUT4000E\n12kw:FSCUT6000",
        "230ayna:FSCUT3000DE-G\n350ayna:FSCUT5000BH",
        "120ayna:\nFSCUT3000DE-A;\n230-350ayna:\nFSCUT3000DE-M",
        "120ayna:\nFSCUT3000DE-A;\n230ayna:\nFSCUT3000DE-M\n350aynaBOCHU kullanır:\nFSCUT3000DE-G",
        "BOCHU\nFSCUT5000S-7 eksen",
        "BOCHU\nFSCUT5000S-7 eksen",
        "BOCHU\nFSCUT5000S-7 eksen"
      ],
      [
        "Lazer kesim kafası",
        "3kw:RayTools BM110\n6kw:BOCI BLT421S\n12kw:BOCI BLT642h\n20kw:BOCI BLT662H\n30kw:BOCI BLT682H\n40kw:BOCI BLT6102H",
        "≤3kw:RayTools BM110\n6kw:RayTools BM06K\n12KW:BOCI BLT442",
        "6kw:BOCI BLT421S\n12kw:BOCI BLT642H\n20kw:BOCI BLT662H\n30kw: BOCI BLT682H\n40kw: BOCI BLT6102H\n60kw: BOCI BLT6120H",
        "≤3kw:RayTools BM110\n6kw:BOCI BLT421S\n12kw:BOCI BLT642H\n20kw:BOCI BLT662H\n30kw:BOCI BLT682H\n40kw:BOCI BLT6102H",
        "≤3kw:RayTools BM110\n6kw:RayTools BM06K\n12KW BOCI BLT442",
        "6kw:BOCI BLT421S\n12kw:BOCI BLT642H\n20kw:BOCI BLT662H\n30kw: BOCI BLT682H\n40kw: BOCI BLT6102H",
        "6kw: BOCI BLT421S\n12kw:BOCI BLT442\n20kw: BOCI BLT462\n30kw: BOCI BLT482\n40kw: BOCI BLT4102",
        "6kw: BOCI BLT421S\n12kw:BOCI BLT442\n20kw: BOCI BLT462\n30kw: BOCI BLT482\n40kw: BOCI BLT4102",
        "≤3kw:RayTools BM110\n6kw:BOCI BLT421S",
        "≤3kw:RayTools BM110\n6kw:BOCI BLT421S\n12kw:BOCI BLT442",
        "≤3kw:Raytools BM110\n6kw:Raytools BM06K\n12KW:Raytools BS12K",
        "≤3kw:Raytools BM110\n6kw:Raytools BM06K\n12KW:Raytools BS12K\n(:TG6012:BLT310T)",
        "≤3kw:Raytools BM110\n6kw:Raytools BM06K\n12KW:Raytools BS12K\n(:TH6012:BLT310T)",
        "≤3kw:Raytools BM110\n6kw:Raytools BM06K\n12KW:Raytools BS12K",
        "≤3kw:Raytools BM110\n6kw:Raytools BM06K\n12KW:Raytools BS12K",
        "≤3kw:Raytools BM110\n6kw:Raytools BM06K\n12KW:Raytools BS12K\n20KW:Raytools BS20K"
      ],
      [
        "Desteklenen güç",
        "1.5kw-20kw",
        "1.5kw-12kw",
        "6kw-200kw",
        "1.5kw-40kw",
        "1.5kw-12kw",
        "6kw-40kw",
        "6kw-40kw",
        "6kw-40kw",
        "1.5kw-6kw",
        "1.5kw-12kw",
        "1.5KW-12KW",
        "1.5kw-12kw",
        "1.5kw-12kw",
        "3kw-12kw",
        "3kw-12kw",
        "3kw-20kw"
      ],
      [
        "Lazer kaynağı",
        "MAX/Raycus",
        "MAX/Raycus",
        "MAX/Raycus",
        "MAX/Raycus",
        "MAX/Raycus",
        "MAX/Raycus",
        "MAX/Raycus",
        "MAX/Raycus",
        "MAX/Raycus",
        "MAX/Raycus",
        "MAX/Raycus",
        "MAX/Raycus",
        "MAX/Raycus",
        "MAX/Raycus",
        "MAX/Raycus",
        "MAX/Raycus"
      ],
      [
        "Desteklenen modeller",
        "F3015/F4015/6015\nF4020/6020\nF6025/6525/12025\nF14031",
        "F3015+T6-230\nF4015+T6-230\nF6015+T6-230\nF4020+T6-230\nF6020+T6-230",
        "GR2500-6/12/16/20\nGR3200-6/12/16/20\nGR4000-6/12/16/20\n(Özelleştirilebilir)",
        "PG3015/6015\nPG4020/6020\nPG6025/6525",
        "PG3015+T6-230\nPG6015+T6-230\nPG4020+T6-230\nPG6020+T6-230\nPG6025+T6-230",
        "H3015/4020/6020",
        "FB3015/FB6020",
        "PB3015/PB6020",
        "R3015/R4015",
        "S1530",
        "TA6020/12020/6035\n9035/12035",
        "TG6012/TG6020/TG6035",
        "TH6012/TH6020/TH6035",
        "TS6020+S6\nTS12035+S6/S12\n(Özelleştirilebilir)",
        "TE12035+E12\n(Özelleştirilebilir)",
        "TZ12055+Z12\n(Özelleştirilebilir)"
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ]
    ],
    "merges": [
      {
        "startRow": 1,
        "endRow": 1,
        "startColumn": 1,
        "endColumn": 17
      }
    ]
  },
  {
    "name": "F Serisi",
    "rows": [
      [
        "Ürün Parametre ve Konfigürasyon Listesi\n● Standart konfigürasyon\n○ Opsiyonel konfigürasyon\n× Konfigürasyon gerektirmez\nNot: 1. Gerçek sevkiyat ağırlığı, sipariş durumuna göre PMC ile teyit edilmelidir;\n2. F Serisi için yüksek toz emiş gereksinimi olan müşteriler, standart dışı toz emiş konfigürasyonu konusunda satış öncesi ekibe danışabilir;\n3. F12025 ve F14031 modellerinin ihracat sevkiyatında açık platform tipi konteyner kullanılmalıdır.",
        "",
        "",
        "",
        "F Serisi",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Sıra No.",
        "Öğe",
        "",
        "Alt öğe",
        "F3015",
        "F4015",
        "F6015",
        "F4020",
        "F6020",
        "F6025",
        "F6525"
      ],
      [
        "1",
        "Temel parametre",
        "",
        "Çalışma alanı",
        "3050*1530mm",
        "4050*1530mm",
        "6050*1530mm",
        "4050*2030mm",
        "6050*2030mm",
        "6050*2530mm",
        "6550*2530mm"
      ],
      [
        "",
        "",
        "",
        "Maksimum hareket hızı",
        "115m/min",
        "115m/min",
        "115m/min",
        "115m/min",
        "115m/min",
        "115m/min",
        "115m/min"
      ],
      [
        "3",
        "Performans",
        "",
        "Konumlandırma hassasiyeti",
        "±0.05mm",
        "±0.05mm",
        "±0.05mm",
        "±0.05mm",
        "±0.05mm",
        "±0.05mm",
        "±0.05mm"
      ],
      [
        "",
        "",
        "",
        "Tekrarlama hassasiyeti",
        "±0.03mm",
        "±0.03mm",
        "±0.03mm",
        "±0.03mm",
        "±0.03mm",
        "±0.03mm",
        "±0.03mm"
      ],
      [
        "",
        "",
        "",
        "Maksimum ivme (X/Y eksenleri eşzamanlı)",
        "0.8G",
        "0.8G",
        "0.8G",
        "0.8G",
        "0.8G",
        "0.8G",
        "0.8G"
      ],
      [
        "",
        "",
        "",
        "Z ekseni hareket mesafesi",
        "100mm",
        "100mm",
        "100mm",
        "100mm",
        "100mm",
        "100mm",
        "100mm"
      ],
      [
        "",
        "",
        "",
        "Tabla taşıma kapasitesi",
        "≤6kw:950kg\n12-20kw:1500kg",
        "≤6kw:1250kg\n12-20kw:1900kg",
        "≤6kw:1850kg\n12-20kw:2950Kg",
        "≤6kw:1650kg\n12-20kw:2500kg",
        "≤6kw:2450kg\n12-20kw:3900kg",
        "≤6kw:3050kg\n12-20kw:4850Kg",
        "≤6kw:3200kg\n12-20kw:5200kg"
      ],
      [
        "",
        "",
        "",
        "Dış ölçüler",
        "4600*2800*2100mm",
        "5700*2800*2100mm",
        "8000*2800*2100mm",
        "5700*3100*2100mm",
        "8000*3100*2100mm",
        "8000*3850*2100mm",
        "8675*3850*2100mm"
      ],
      [
        "",
        "",
        "",
        "Toplam ağırlık",
        "≤6kw:2150kg\n12-20kw:3150kg",
        "≤6kw:2410kg\n12-20kw:3760kg",
        "≤6kw:2840kg\n12-20kw:4640kg",
        "≤6kw:3150kg\n12-20kw:4950kg",
        "≤6kw:4150kg\n12-20kw:6850kg",
        "≤6kw:4530kg\n12-20kw:8030kg",
        "≤6kw:5100kg\n12-20kw:8600kg"
      ],
      [
        "",
        "",
        "",
        "Modelin desteklediği güç",
        "1.5-20kw",
        "1.5-20kw",
        "1.5-20kw",
        "1.5-20kw",
        "1.5-20kw",
        "1.5-20kw",
        "1.5-20kw"
      ],
      [
        "4",
        "Konfigürasyon",
        "Mekanik sistem",
        "Gövde",
        "Kaynaklı gövde",
        "Kaynaklı gövde",
        "Kaynaklı gövde",
        "Kaynaklı gövde",
        "Kaynaklı gövde",
        "Kaynaklı gövde",
        "Kaynaklı gövde"
      ],
      [
        "",
        "",
        "",
        "Kiriş",
        "Havacılık sınıfı alüminyum profil",
        "Havacılık sınıfı alüminyum profil",
        "Havacılık sınıfı alüminyum profil",
        "Havacılık sınıfı alüminyum profil",
        "Havacılık sınıfı alüminyum profil",
        "Havacılık sınıfı alüminyum profil",
        "Havacılık sınıfı alüminyum profil"
      ],
      [
        "",
        "",
        "",
        "Y ekseni motor gücü",
        "≤6kw:0.85KW*2\n8-20kw:1.8KW*2",
        "≤6kw:0.85KW*2\n8-20kw:1.8KW*2",
        "≤6kw:0.85KW*2\n8-20kw:1.8KW*2",
        "≤6kw:0.85KW*2\n8-20kw:1.8KW*2",
        "≤6kw:0.85KW*2\n8-20kw:1.8KW*2",
        "≤6kw:0.85KW*2\n8-20kw:1.8KW*2",
        "≤6kw:0.85KW*2\n8-20kw:1.8KW*2"
      ],
      [
        "",
        "",
        "",
        "X ekseni motor gücü",
        "≤6kw:0.85KW\n8-20kw:1.3KW",
        "≤6kw:0.85KW\n8-20kw:1.3KW",
        "≤6kw:0.85KW\n8-20kw:1.3KW",
        "≤6kw:0.85KW\n8-20kw:1.3KW",
        "≤6kw:0.85KW\n8-20kw:1.3KW",
        "≤6kw:0.85KW\n8-20kw:1.3KW",
        "≤6kw:0.85KW\n8-20kw:1.3KW"
      ],
      [
        "",
        "",
        "",
        "Z ekseni motor gücü",
        "≤6kw:0.4KW\n8-20kw:0.75KW",
        "≤6kw:0.4KW\n8-20kw:0.75KW",
        "≤6kw:0.4KW\n8-20kw:0.75KW",
        "≤6kw:0.4KW\n8-20kw:0.75KW",
        "≤6kw:0.4KW\n8-20kw:0.75KW",
        "≤6kw:0.4KW\n8-20kw:0.75KW",
        "≤6kw:0.4KW\n8-20kw:0.75KW"
      ],
      [
        "",
        "",
        "",
        "Y ekseni lineer kızak modeli",
        "25#",
        "25#",
        "25#",
        "25#",
        "25#",
        "25#",
        "25#"
      ],
      [
        "",
        "",
        "",
        "X ekseni lineer kızak modeli",
        "20#",
        "20#",
        "20#",
        "20#",
        "20#",
        "20#",
        "20#"
      ],
      [
        "",
        "",
        "",
        "Z ekseni lineer kızak modeli",
        "15#",
        "15#",
        "15#",
        "15#",
        "15#",
        "15#",
        "15#"
      ],
      [
        "",
        "",
        "",
        "Vidalı mil",
        "TBI",
        "TBI",
        "TBI",
        "TBI",
        "TBI",
        "TBI",
        "TBI"
      ],
      [
        "",
        "",
        "Çevre birimleri sistemi",
        "Santrifüj fan",
        "●",
        "●",
        "●",
        "●",
        "●",
        "●",
        "●"
      ],
      [
        "",
        "",
        "",
        "Atık toplama arabası adedi",
        "3 grup (6 adet)",
        "4 grup (8 adet)",
        "6 grup (12 adet)",
        "4 grup (8 adet)",
        "6 grup (12 adet)",
        "6 grup (18 adet)",
        "7 grup (21 adet)"
      ],
      [
        "",
        "",
        "",
        "Kesim sisteminin tanıdığı dosya formatları",
        "DXF, LXD, PLT, AI, Gerber vb. grafik veri formatlarını destekler,\nLantek, CNCkad vb. yazılımların ürettiği uluslararası standart G kodlarını kabul eder.",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "Diğer parametre konfigürasyonları",
        "Giriş güç parametreleri",
        "380V±5%/\n50-60Hz",
        "380V±5%/\n50-60Hz",
        "380V±5%/\n50-60Hz",
        "380V±5%/\n50-60Hz",
        "380V±5%/\n50-60Hz",
        "380V±5%/\n50-60Hz",
        "380V±5%/\n50-60Hz"
      ],
      [
        "",
        "",
        "",
        "1,5 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
        "13.9KW/30KVA",
        "13.9KW/30KVA",
        "13.9KW/30KVA",
        "13.9KW/30KVA",
        "13.9KW/30KVA",
        "15.4KW/30KVA",
        "15.4KW/30KVA"
      ],
      [
        "",
        "",
        "",
        "2 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
        "14.6KW/30KVA",
        "14.6KW/30KVA",
        "14.6KW/30KVA",
        "14.6KW/30KVA",
        "14.6KW/30KVA",
        "16.1KW/30KVA",
        "16.1KW/30KVA"
      ],
      [
        "",
        "",
        "",
        "3 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
        "21.4KW/40KVA",
        "21.4KW/40KVA",
        "21.4KW/40KVA",
        "21.4KW/40KVA",
        "21.4KW/40KVA",
        "22.9KW/40KVA",
        "22.9KW/40KVA"
      ],
      [
        "",
        "",
        "",
        "6 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
        "35.9KW/50KVA",
        "35.9KW/50KVA",
        "35.9KW/50KVA",
        "35.9KW/50KVA",
        "35.9KW/50KVA",
        "36.9KW/60KVA",
        "36.9KW/60KVA"
      ],
      [
        "",
        "",
        "",
        "12 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
        "55.9KW/80KVA",
        "55.9KW/80KVA",
        "55.9KW/80KVA",
        "55.9KW/80KVA",
        "55.9KW/80KVA",
        "57.4kW/80KVA",
        "57.4kW/80KVA"
      ],
      [
        "",
        "",
        "",
        "20 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
        "101.6KW/150KVA",
        "101.6KW/150KVA",
        "101.6KW/150KVA",
        "101.6KW/150KVA",
        "101.6KW/150KVA",
        "103.1KW/150KVA",
        "103.1KW/150KVA"
      ],
      [
        "",
        "",
        "",
        "40 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
        "/",
        "/",
        "/",
        "/",
        "/",
        "/",
        "/"
      ]
    ],
    "merges": [
      {
        "startRow": 14,
        "endRow": 22,
        "startColumn": 3,
        "endColumn": 3
      },
      {
        "startRow": 14,
        "endRow": 33,
        "startColumn": 2,
        "endColumn": 2
      },
      {
        "startRow": 25,
        "endRow": 25,
        "startColumn": 5,
        "endColumn": 11
      },
      {
        "startRow": 1,
        "endRow": 2,
        "startColumn": 1,
        "endColumn": 4
      },
      {
        "startRow": 3,
        "endRow": 3,
        "startColumn": 2,
        "endColumn": 3
      },
      {
        "startRow": 4,
        "endRow": 5,
        "startColumn": 1,
        "endColumn": 1
      },
      {
        "startRow": 26,
        "endRow": 33,
        "startColumn": 3,
        "endColumn": 3
      },
      {
        "startRow": 14,
        "endRow": 33,
        "startColumn": 1,
        "endColumn": 1
      },
      {
        "startRow": 6,
        "endRow": 13,
        "startColumn": 2,
        "endColumn": 3
      },
      {
        "startRow": 23,
        "endRow": 25,
        "startColumn": 3,
        "endColumn": 3
      },
      {
        "startRow": 6,
        "endRow": 13,
        "startColumn": 1,
        "endColumn": 1
      },
      {
        "startRow": 1,
        "endRow": 2,
        "startColumn": 5,
        "endColumn": 11
      },
      {
        "startRow": 4,
        "endRow": 5,
        "startColumn": 2,
        "endColumn": 3
      }
    ]
  },
  {
    "name": "PG Serisi",
    "rows": [
      [
        "Ürün Parametre ve Konfigürasyon Listesi\n● Standart konfigürasyon\n○ Opsiyonel konfigürasyon\n× Konfigürasyon gerektirmez\nNot: 1. Gerçek sevkiyat ağırlığı, sipariş durumuna göre PMC ile teyit edilmelidir;\n2. PG modelinde standart dışı pah uygulamasında pah kesim yalnızca üst tabla üzerinde yapılabilir;",
        "",
        "",
        "",
        "PG Serisi",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Sıra No.",
        "Öğe",
        "",
        "Alt öğe",
        "PG3015",
        "PG6015",
        "PG4020",
        "PG6020",
        "PG6025",
        "PG6525",
        ""
      ],
      [
        "1",
        "Temel parametre",
        "",
        "Standart düz kesim çalışma alanı",
        "3050*1530",
        "6050*1530",
        "4050*2030",
        "6050*2030",
        "6050*2530",
        "6550*2530",
        ""
      ],
      [
        "",
        "",
        "",
        "Maksimum hareket hızı",
        "115m/min",
        "120m/min",
        "120m/min",
        "120m/min",
        "120m/min",
        "120m/min",
        ""
      ],
      [
        "3",
        "Performans",
        "",
        "Konumlandırma hassasiyeti",
        "±0.03mm/m",
        "±0.03mm/m",
        "±0.03mm/m",
        "±0.03mm/m",
        "±0.03mm/m",
        "±0.03mm/m",
        ""
      ],
      [
        "",
        "",
        "",
        "Tekrarlama hassasiyeti",
        "±0.02mm",
        "±0.02mm",
        "±0.02mm",
        "±0.02mm",
        "±0.02mm",
        "±0.02mm",
        ""
      ],
      [
        "",
        "",
        "",
        "Maksimum ivme (X/Y eksenleri eşzamanlı)",
        "1.5G",
        "1.5G",
        "1.5G",
        "1.5G",
        "1.5G",
        "1.5G",
        ""
      ],
      [
        "",
        "",
        "",
        "Z ekseni hareket mesafesi",
        "315mm",
        "375mm",
        "375mm",
        "375mm",
        "375mm",
        "375mm",
        ""
      ],
      [
        "",
        "",
        "",
        "Tabla değişim süresi",
        "10-15S(ayarlanabilir)",
        "18-30(ayarlanabilir)",
        "12-20S(ayarlanabilir)",
        "18-30(ayarlanabilir)",
        "18-30(ayarlanabilir)",
        "20-35S(ayarlanabilir)",
        ""
      ],
      [
        "",
        "",
        "",
        "Tabla taşıma kapasitesi",
        "1440kg",
        "≤20KW 2880kg\n≥30KW 4320kg",
        "≤20KW 2560kg\n≥30KW 3840kg",
        "≤20KW 3840kg\n≥30KW 5760kg",
        "≤20KW 4800kg\n≥30KW 7200kg",
        "≤20KW 5100kg\n≥30KW 7650kg",
        ""
      ],
      [
        "",
        "",
        "",
        "Dış ölçüler",
        "8270*2280*2150mm",
        "14580*2880*2350mm",
        "10570*3430*2350mm",
        "14580*3430*2350mm",
        "14580*3930*2350mm",
        "15500*3930*2350mm",
        ""
      ],
      [
        "",
        "",
        "",
        "Toplam ağırlık",
        "≤6kw:4450kg\n12-20kw:5500kg",
        "≤6kw:9900kg\n12-40kw:10300kg",
        "≤6kw:8100kg\n12-40kw:8500kg",
        "≤6kw:11000kg\n12-40kw:11600kg",
        "≤6kw:12000kg\n12--40kw:12700kg",
        "≤6kw:14200kg\n12-40kw:15000kg",
        ""
      ],
      [
        "",
        "",
        "",
        "Modelin desteklediği güç",
        "1.5-20KW",
        "1.5-40KW",
        "1.5-40KW",
        "1.5-40KW",
        "1.5-40KW",
        "1.5-40KW",
        ""
      ],
      [
        "4",
        "Konfigürasyon",
        "Mekanik sistem",
        "Gövde",
        "Kaynaklı gövde",
        "Kaynaklı gövde",
        "Kaynaklı gövde",
        "Kaynaklı gövde",
        "Kaynaklı gövde",
        "Kaynaklı gövde",
        ""
      ],
      [
        "",
        "",
        "",
        "Kiriş",
        "Havacılık sınıfı alüminyum profil",
        "Havacılık sınıfı alüminyum profil",
        "Havacılık sınıfı alüminyum profil",
        "Havacılık sınıfı alüminyum profil",
        "Havacılık sınıfı alüminyum profil",
        "Havacılık sınıfı alüminyum profil",
        ""
      ],
      [
        "",
        "",
        "",
        "Y ekseni motor gücü",
        "≤6kW 1.3KW*2\n≥8KW 1.8KW*2",
        "6kW 1.8KW*2\n≥8KW 2.9KW*2",
        "6kW 1.8KW*2\n≥8KW 2.9KW*2",
        "6kW 1.8KW*2\n≥8KW 2.9KW*2",
        "6kW 1.8KW*2\n≥8KW 2.9KW*2",
        "6kW 1.8KW*2\n≥8KW 2.9KW*2",
        ""
      ],
      [
        "",
        "",
        "",
        "X ekseni motor gücü",
        "0.85KW",
        "1.3KW",
        "1.3KW",
        "1.3KW",
        "1.3KW",
        "1.3KW",
        ""
      ],
      [
        "",
        "",
        "",
        "Z ekseni motor gücü",
        "≤6kW 0.4KW\n≥8KW 0.75KW",
        "0.75KW",
        "0.75KW",
        "0.75KW",
        "0.75KW",
        "0.75KW",
        ""
      ],
      [
        "",
        "",
        "",
        "Tabla değişim motor gücü",
        "1.1KW",
        "≤6kW 1.5KW\n≥8KW 1.1KW*2",
        "≤6kW 1.5KW\n≥8KW 1.1KW*2",
        "≤6kW 1.5KW\n≥8KW 1.5KW*2",
        "≤6kW 1.5KW\n≥8KW 1.5KW*2",
        "≤6kW 1.5KW\n≥8KW 1.5KW*2",
        ""
      ],
      [
        "",
        "",
        "",
        "Y ekseni lineer kızak modeli",
        "30#",
        "30#",
        "30#",
        "30#",
        "30#",
        "30#",
        ""
      ],
      [
        "",
        "",
        "",
        "X ekseni lineer kızak modeli",
        "20#",
        "25#",
        "25#",
        "25#",
        "25#",
        "25#",
        ""
      ],
      [
        "",
        "",
        "",
        "Z ekseni lineer kızak modeli",
        "15#",
        "20#",
        "20#",
        "20#",
        "20#",
        "20#",
        ""
      ],
      [
        "",
        "",
        "",
        "Vidalı mil",
        "TBI",
        "TBI",
        "TBI",
        "TBI",
        "TBI",
        "TBI",
        ""
      ],
      [
        "",
        "",
        "Çevre birimleri sistemi",
        "Santrifüj fan",
        "●",
        "●",
        "●",
        "●",
        "●",
        "●",
        ""
      ],
      [
        "",
        "",
        "",
        "Atık toplama arabası adedi",
        "3 grup (6 adet)",
        "5 grup (10 adet)",
        "3 grup (6 adet)",
        "5 grup (10 adet)",
        "5 grup (15 adet)",
        "5 grup (15 adet)",
        ""
      ],
      [
        "",
        "",
        "",
        "Kesim sisteminin tanıdığı dosya formatları",
        "DXF, LXD, PLT, AI, Gerber vb. grafik veri formatlarını destekler,\nLantek, CNCkad vb. yazılımların ürettiği uluslararası standart G kodlarını kabul eder.",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "Diğer parametre konfigürasyonları",
        "Giriş güç parametreleri",
        "380V±5%/\n50-60Hz",
        "380V±5%/\n50-60Hz",
        "380V±5%/\n50-60Hz",
        "380V±5%/\n50-60Hz",
        "380V±5%/\n50-60Hz",
        "380V±5%/\n50-60Hz",
        ""
      ],
      [
        "",
        "",
        "",
        "1,5 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
        "17.5KW/30KVA",
        "17.9KW/30KVA",
        "18.9KW/30KVA",
        "18.9KW/30KVA",
        "18.9KW/30KVA",
        "18.9KW/30KVA",
        ""
      ],
      [
        "",
        "",
        "",
        "2 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
        "18.2KW/30KVA",
        "18.6KW/30KVA",
        "19.6KW/40KVA",
        "19.6KW/40KVA",
        "19.6KW/40KVA",
        "19.6KW/40KVA",
        ""
      ],
      [
        "",
        "",
        "",
        "3 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
        "25KW/40KVA",
        "25.4KW/40KVA",
        "26.4KW/40KVA",
        "26.4KW/40KVA",
        "26.4KW/40KVA",
        "26.4KW/40KVA",
        ""
      ],
      [
        "",
        "",
        "",
        "6 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
        "37KW/60KVA",
        "37.4KW/60KVA",
        "38.4KW/60KVA",
        "38.4KW/60KVA",
        "38.4KW/60KVA",
        "38.4KW/60KVA",
        ""
      ],
      [
        "",
        "",
        "",
        "12 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
        "70.8KW/100KVA",
        "71.5KW/100KVA",
        "71.5KW/100KVA",
        "72.3KW/100KVA",
        "72.3KW/100KVA",
        "72.3KW/100KVA",
        ""
      ],
      [
        "",
        "",
        "",
        "20 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
        "106.8KW/150KVA",
        "107.5KW/150KVA",
        "107.5KW/150KVA",
        "108.3KW/150KVA",
        "108.3KW/150KVA",
        "108.3KW/150KVA",
        ""
      ],
      [
        "",
        "",
        "",
        "30 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
        "/",
        "155KW/200KVA",
        "155KW/200KVA",
        "155.8KW/200KVA",
        "155.8KW/200KVA",
        "155.8KW/200KVA",
        ""
      ],
      [
        "",
        "",
        "",
        "40 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
        "/",
        "229.5KW/300KVA",
        "229.5KW/300KVA",
        "230.5KW/300KVA",
        "230.5KW/300KVA",
        "230.5KW/300KVA",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ]
    ],
    "merges": [
      {
        "startRow": 1,
        "endRow": 1,
        "startColumn": 1,
        "endColumn": 4
      },
      {
        "startRow": 1,
        "endRow": 1,
        "startColumn": 5,
        "endColumn": 10
      },
      {
        "startRow": 27,
        "endRow": 35,
        "startColumn": 3,
        "endColumn": 3
      },
      {
        "startRow": 5,
        "endRow": 13,
        "startColumn": 1,
        "endColumn": 1
      },
      {
        "startRow": 2,
        "endRow": 2,
        "startColumn": 2,
        "endColumn": 3
      },
      {
        "startRow": 14,
        "endRow": 35,
        "startColumn": 1,
        "endColumn": 1
      },
      {
        "startRow": 3,
        "endRow": 4,
        "startColumn": 1,
        "endColumn": 1
      },
      {
        "startRow": 5,
        "endRow": 13,
        "startColumn": 2,
        "endColumn": 3
      },
      {
        "startRow": 14,
        "endRow": 23,
        "startColumn": 3,
        "endColumn": 3
      },
      {
        "startRow": 26,
        "endRow": 26,
        "startColumn": 5,
        "endColumn": 10
      },
      {
        "startRow": 14,
        "endRow": 35,
        "startColumn": 2,
        "endColumn": 2
      },
      {
        "startRow": 24,
        "endRow": 26,
        "startColumn": 3,
        "endColumn": 3
      },
      {
        "startRow": 3,
        "endRow": 4,
        "startColumn": 2,
        "endColumn": 3
      }
    ]
  },
  {
    "name": "TG Serisi",
    "rows": [
      [
        "Ürün Parametre ve Konfigürasyon Listesi\n● Standart konfigürasyon\n○ Opsiyonel konfigürasyon\n× Konfigürasyon gerektirmez\nNot: Gerçek sevkiyat ağırlığı, sipariş durumuna göre PMC ile teyit edilmelidir.",
        "",
        "",
        "",
        "TG Serisi",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "Sıra No.",
        "Öğe",
        "",
        "Alt öğe",
        "TG6012",
        "TG6020",
        "TG6035"
      ],
      [
        "1",
        "Temel parametre",
        "",
        "Boru kesit şekli",
        "Yuvarlak, kare, dikdörtgen, oval, oblong boru; köşebent, U profil vb.\nDiğer kesit şekilleri için ürün yöneticisine danışınız",
        "Yuvarlak boru, kare boru, dikdörtgen boru, U profil, köşebent, I profil vb.\nDiğer kesit şekilleri için ürün yöneticisine danışınız",
        "Yuvarlak boru, kare boru, dikdörtgen boru, U profil, köşebent, I profil vb.\nDiğer kesit şekilleri için ürün yöneticisine danışınız"
      ],
      [
        "",
        "",
        "",
        "Boru ölçü aralığı",
        "Yuvarlak boruφ10-120mm\nKare boru10*10-120*120mm\nDiğer ölçüler için ayna sıkma şemasına bakınız",
        "Yuvarlak boruφ15-230mm\nKare boru15*15-230*230mm\nDiğer ölçüler için ayna sıkma şemasına bakınız",
        "Yuvarlak boruφ20-350mm\nKare boru20*20-350*350mm\nDiğer ölçüler için ayna sıkma şemasına bakınız"
      ],
      [
        "",
        "",
        "",
        "Boru gereksinimleri",
        "Boru çapı＜φ50mm Boru et kalınlığı≥1.2mm;\nBoru çapı ≥ φ50 mm\nİnce cidarlı borularda et kalınlığı/çap oranı 1/40'tan az olmamalıdır",
        "Boru çapı＜φ50mm Boru et kalınlığı≥1.2mm;\nBoru çapı ≥ φ50 mm\nİnce cidarlı borularda et kalınlığı/çap oranı 1/40'tan az olmamalıdır",
        "Boru çapı＜φ50mm Boru et kalınlığı≥1.2mm;\nBoru çapı ≥ φ50 mm\nİnce cidarlı borularda et kalınlığı/çap oranı 1/40'tan az olmamalıdır"
      ],
      [
        "",
        "",
        "",
        "Maksimum işlenebilir boru uzunluğu",
        "6300mm",
        "6300mm",
        "6300mm"
      ],
      [
        "",
        "",
        "",
        "Tek boru için maksimum ağırlık",
        "100kg",
        "300kg",
        "900kg"
      ],
      [
        "",
        "",
        "",
        "En kısa artık malzeme",
        "45mm",
        "70mm",
        "120mm"
      ],
      [
        "",
        "",
        "",
        "Dış ölçüler (ihracat)",
        "8750*1490*2210mm",
        "8870*1500*2220mm",
        "9280*1720*2300mm"
      ],
      [
        "",
        "",
        "",
        "Toplam ağırlık (ihracat)",
        "2230kg",
        "2550kg",
        "4760kg"
      ],
      [
        "3",
        "Performans",
        "",
        "Konumlandırma hassasiyeti",
        "±0.05mm/m",
        "±0.05mm/m",
        "±0.05mm/m"
      ],
      [
        "",
        "",
        "",
        "Tekrarlama hassasiyeti",
        "±0.03mm/m",
        "±0.03mm/m",
        "±0.03mm/m"
      ],
      [
        "",
        "",
        "",
        "Maksimum ayna dönüş hızı",
        "200r/min",
        "120r/min",
        "80r/min"
      ],
      [
        "",
        "",
        "",
        "Ayna besleme ekseni maksimum hızı",
        "130m/min",
        "110m/min",
        "80m/min"
      ],
      [
        "",
        "",
        "",
        "Ayna besleme ekseni maksimum ivmesi",
        "1.5G",
        "1.5G",
        "0.8G"
      ],
      [
        "",
        "",
        "Elektrik sistemi",
        "Y ekseni motor gücü",
        "1.8kw",
        "2.9kw",
        "4.4kw"
      ],
      [
        "",
        "",
        "",
        "X ekseni motor gücü",
        "0.75kw",
        "0.75kw",
        "0.75kw"
      ],
      [
        "",
        "",
        "",
        "Z ekseni motor gücü",
        "0.75kw",
        "0.75kw",
        "0.75kw"
      ],
      [
        "",
        "",
        "",
        "B ekseni motor gücü",
        "1.8kw+1.3kw",
        "2.9kw+1.8kw",
        "4.4kw+2.9kw"
      ],
      [
        "",
        "",
        "",
        "Kontrol sistemi tipi",
        "EtherCAT veri yolu kontrolü",
        "EtherCAT veri yolu kontrolü",
        "EtherCAT veri yolu kontrolü"
      ],
      [
        "",
        "",
        "",
        "Bağımsız elektrik kontrol kabini",
        "×",
        "×",
        "×"
      ],
      [
        "",
        "",
        "",
        "Boru nestleme yazılımı",
        "● (Temel sürüm)",
        "● (Temel sürüm)",
        "● (Temel sürüm)"
      ],
      [
        "",
        "",
        "",
        "Ekran boyutu",
        "21.5 inç",
        "21.5 inç",
        "21.5 inç"
      ],
      [
        "",
        "",
        "",
        "Sistemin tanıdığı dosya formatı",
        "zx、zzx",
        "zx、zzx",
        "zx、zzx"
      ],
      [
        "",
        "",
        "Çevre birimleri sistemi",
        "Su soğutucu",
        "AORE standart konfigürasyonu (Hanli)",
        "AORE standart konfigürasyonu (Hanli)",
        "AORE standart konfigürasyonu (Hanli)"
      ],
      [
        "",
        "",
        "",
        "Santrifüj fan",
        "●",
        "●",
        "●"
      ],
      [
        "",
        "",
        "",
        "Toz emiş fanı gücü",
        "1.5Kw",
        "1.5Kw",
        "1.5Kw"
      ],
      [
        "",
        "",
        "Diğer parametre konfigürasyonları",
        "Giriş güç parametreleri",
        "380V±5%/\n50-60Hz",
        "380V±5%/\n50-60Hz",
        "380V±5%/\n50-60Hz"
      ],
      [
        "",
        "",
        "",
        "Modelin desteklediği güç",
        "1.5-3kw",
        "1.5-6kw",
        "3kw-12kw"
      ],
      [
        "",
        "",
        "",
        "1,5 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
        "21.1kw/40KVA",
        "23.8kw/40KVA",
        "26.6kw/40KVA"
      ],
      [
        "",
        "",
        "",
        "2 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
        "21.8kw/40KVA",
        "24.5kw/40KVA",
        "29.8kw/40KVA"
      ],
      [
        "",
        "",
        "",
        "3 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
        "28.6kw/40KVA",
        "31.3kw/40KVA",
        "32.22kw/40KVA"
      ],
      [
        "",
        "",
        "",
        "6 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
        "29.2kw/50KVA",
        "31.9kw/50KVA",
        "45.3kw/60KVA"
      ],
      [
        "",
        "",
        "",
        "12 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
        "\\",
        "\\",
        "73.6kw/100KVA"
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ],
      [
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ]
    ],
    "merges": [
      {
        "startRow": 4,
        "endRow": 11,
        "startColumn": 2,
        "endColumn": 3
      },
      {
        "startRow": 1,
        "endRow": 2,
        "startColumn": 5,
        "endColumn": 7
      },
      {
        "startRow": 12,
        "endRow": 16,
        "startColumn": 1,
        "endColumn": 1
      },
      {
        "startRow": 1,
        "endRow": 2,
        "startColumn": 1,
        "endColumn": 4
      },
      {
        "startRow": 4,
        "endRow": 11,
        "startColumn": 1,
        "endColumn": 1
      },
      {
        "startRow": 17,
        "endRow": 25,
        "startColumn": 3,
        "endColumn": 3
      },
      {
        "startRow": 3,
        "endRow": 3,
        "startColumn": 2,
        "endColumn": 3
      },
      {
        "startRow": 12,
        "endRow": 16,
        "startColumn": 2,
        "endColumn": 3
      },
      {
        "startRow": 29,
        "endRow": 35,
        "startColumn": 3,
        "endColumn": 3
      },
      {
        "startRow": 17,
        "endRow": 35,
        "startColumn": 2,
        "endColumn": 2
      },
      {
        "startRow": 17,
        "endRow": 35,
        "startColumn": 1,
        "endColumn": 1
      },
      {
        "startRow": 26,
        "endRow": 28,
        "startColumn": 3,
        "endColumn": 3
      }
    ]
  }
];

export const AORE_LABEL_ALIASES: Record<string, string> = {
  "———— 海外设备配置说明表 2025.03.18————": "———— Yurt Dışı Ekipman Konfigürasyon Açıklama Tablosu 2025.03.18 ————",
  "系列": "Seri",
  "伺服电机Servo Motor": "Servo motor",
  "导轨guide": "Lineer kızak",
  "齿条rack": "Kremayer",
  "减速机Reducer": "Redüktör",
  "水冷机Water Cooler": "Su soğutucu",
  "电气元件Electronic components": "Elektrik bileşenleri",
  "比例阀Proportional valve": "Oransal valf",
  "控制系统Control provided": "Kontrol sistemi",
  "切割头Laser Head": "Lazer kesim kafası",
  "支持功率Support power": "Desteklenen güç",
  "激光器Laser source": "Lazer kaynağı",
  "支持机型Supported models": "Desteklenen modeller",
  "子项": "Alt öğe",
  "幅面\nFormat": "Çalışma alanı",
  "最大运行速度\nMax. running speed": "Maksimum hareket hızı",
  "定位精度\nPositioning accuracy": "Konumlandırma hassasiyeti",
  "重复定位精度\nRepositioning accuracy": "Tekrarlama hassasiyeti",
  "最大加速度（X/Y轴联动）\nMax. acceleration（X/Y axis linkage)": "Maksimum ivme (X/Y eksenleri eşzamanlı)",
  "Z轴行程\nZ-axis length of travel": "Z ekseni hareket mesafesi",
  "台面承重\nTable load bearing": "Tabla taşıma kapasitesi",
  "外形尺寸\nDimensions": "Dış ölçüler",
  "总重\nOverall weight": "Toplam ağırlık",
  "机型支持功率\nModel support power": "Modelin desteklediği güç",
  "床身\nBed": "Gövde",
  "横梁\nCrossbeam": "Kiriş",
  "Y轴电机功率\nY-axis motor power": "Y ekseni motor gücü",
  "X轴电机功率\nX-axis motor power": "X ekseni motor gücü",
  "Z轴电机功率\nZ-axis motor power": "Z ekseni motor gücü",
  "Y轴导轨型号\nY-axis guide rail model": "Y ekseni lineer kızak modeli",
  "X轴导轨型号\nX-axis guide rail model": "X ekseni lineer kızak modeli",
  "Z轴导轨型号\nZ-axis guide rail model": "Z ekseni lineer kızak modeli",
  "丝杠\nScrew": "Vidalı mil",
  "离心风机\ncentrifugal fan": "Santrifüj fan",
  "接料小车数量\nQuantity of waste receiving trolley": "Atık toplama arabası adedi",
  "切割系统识别文件格式\nCutting system identification file format": "Kesim sisteminin tanıdığı dosya formatları",
  "输入电源参数\nInput power parameters": "Giriş güç parametreleri",
  "整机总功率/稳压变压器容量（配1.5KW激光器）\nTotal power/transformer capacity with 1.5KW source": "1,5 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
  "整机总功率/稳压变压器容量（配2KW激光器）\nTotal power/transformer capacity with 2KW source": "2 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
  "整机总功率/稳压变压器容量（配3KW激光器）\nTotal power/transformer capacity with 3KW source": "3 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
  "整机总功率/稳压变压器容量（配6KW激光器）\nTotal power/transformer capacity with 6KW source": "6 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
  "整机总功率/稳压变压器容量（配12KW激光器）\nTotal power/transformer capacity with 12KW source": "12 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
  "整机总功率/稳压变压器容量（配20KW激光器）\nTotal power/transformer capacity with 20KW source": "20 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
  "整机总功率/稳压变压器容量（配40KW激光器）\nTotal power/transformer capacity with 40KW source": "40 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
  "常规直切幅面\nConventional straight cut format": "Standart düz kesim çalışma alanı",
  "台面交换时间\nExchange time of platforms": "Tabla değişim süresi",
  "台面交换电机功率\nTable exchange motor pow": "Tabla değişim motor gücü",
  "整机总功率/稳压变压器容量（配30KW激光器）\nTotal power/transformer capacity with 30KW source": "30 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
  "子项\nSubitem": "Alt öğe",
  "管材截面形状\ntube cross-sectional shape": "Boru kesit şekli",
  "管材尺寸范围\ntube size range": "Boru ölçü aralığı",
  "管材要求\nRequirements for tubes": "Boru gereksinimleri",
  "最大加工管材长度\nMax. processing tube length": "Maksimum işlenebilir boru uzunluğu",
  "单根管材最大重量\nMaximum tube weight": "Tek boru için maksimum ağırlık",
  "最短余料\nShortest remaining material": "En kısa artık malzeme",
  "外形尺寸（外贸）\nDimensions": "Dış ölçüler (ihracat)",
  "总重（外贸）\nOverall weight": "Toplam ağırlık (ihracat)",
  "卡盘最大转速\nMax. Chuck rotating speed": "Maksimum ayna dönüş hızı",
  "卡盘送料轴最大速度\nY axis maximum speed": "Ayna besleme ekseni maksimum hızı",
  "卡盘送料轴最大加速度\nX maximum acceleration": "Ayna besleme ekseni maksimum ivmesi",
  "B轴电机功率\nB-axis motor power": "B ekseni motor gücü",
  "控制系统方式\nControl system mode": "Kontrol sistemi tipi",
  "独立电控柜\nIndependent electric control cabinet": "Bağımsız elektrik kontrol kabini",
  "管材套料软件\nControl system": "Boru nestleme yazılımı",
  "显示器尺寸\nDisplay size": "Ekran boyutu",
  "系统识别文件格式\nFile format": "Sistemin tanıdığı dosya formatı",
  "水冷机\nWater Chiller": "Su soğutucu",
  "除尘风机功率\nPower of dust removal fan": "Toz emiş fanı gücü",
  "整机总功率/稳压变压器容量（配1.5kw激光器）\nTotal power/transformer capacity with 1.5kw source": "1,5 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
  "整机总功率/稳压变压器容量（配2kw激光器）\nTotal power/transformer capacity with 2kw source": "2 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
  "整机总功率/稳压变压器容量（配3kw激光器）\nTotal power/transformer capacity with 3kw source": "3 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
  "整机总功率/稳压变压器容量（配6kw激光器）\nTotal power/transformer capacity with 6kw source": "6 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi",
  "整机总功率/稳压变压器容量（配12kw激光器）\nTotal power/transformer capacity with 12kw source": "12 kW lazer kaynağı ile makine toplam gücü / regülatör-trafo kapasitesi"
};
