/**
 * Centralized seed payloads. Re-used by both SQL files in /database/seeds/ and
 * the TS seed scripts in apps/api/src/db/seed/*.
 */

export const lookupRows = {
  pipeline_stages: [
    { code: 'lead', name: 'Lead', sortOrder: 10 },
    { code: 'call', name: 'Arama', sortOrder: 20 },
    { code: 'visit', name: 'Ziyaret', sortOrder: 30 },
    { code: 'quote', name: 'Teklif', sortOrder: 40 },
    { code: 'sales', name: 'Satış', sortOrder: 50 },
    { code: 'cancelled', name: 'İptal', sortOrder: 60 },
    { code: 'proforma', name: 'Proforma', sortOrder: 70 },
    { code: 'contract', name: 'Sözleşme', sortOrder: 80 },
    { code: 'payment_plan', name: 'Ödeme Planı', sortOrder: 85 },
    { code: 'commercial_invoice', name: 'Ticari Fatura', sortOrder: 90 },
    { code: 'customs_approved', name: 'Gümrük Onayı', sortOrder: 100 },
    { code: 'stock_picking', name: 'Stoktan Seçme', sortOrder: 110 },
    { code: 'shipping', name: 'Sevkiyat', sortOrder: 120 },
    { code: 'installation', name: 'Kurulum', sortOrder: 130 },
    { code: 'delivered', name: 'Teslim Edildi', sortOrder: 140 },
  ],
  quote_statuses: [
    { code: 'draft', name: 'Taslak', sortOrder: 10 },
    { code: 'sent', name: 'Gönderildi', sortOrder: 20 },
    { code: 'approved', name: 'Onaylandı', sortOrder: 30 },
    { code: 'rejected', name: 'Reddedildi', sortOrder: 40 },
    { code: 'expired', name: 'Süresi Doldu', sortOrder: 50 },
    { code: 'pending_super_admin_approval', name: 'Süper Admin Onayı Bekliyor', sortOrder: 60 },
    { code: 'cancelled', name: 'İptal', sortOrder: 70 },
    { code: 'price_waiting', name: 'Fiyat Bekleniyor', sortOrder: 80 },
    { code: 'budget_waiting', name: 'Bütçe Bekleniyor', sortOrder: 90 },
    { code: 'on_hold', name: 'Askıya Alındı', sortOrder: 100 },
    { code: 'postponed', name: 'Ertelendi', sortOrder: 110 },
  ],
  sales_order_statuses: [
    { code: 'draft', name: 'Taslak', sortOrder: 10 },
    { code: 'pending_super_admin_approval', name: 'Süper Admin Onayı Bekliyor', sortOrder: 15 },
    { code: 'confirmed', name: 'Onaylandı', sortOrder: 20 },
    { code: 'reserved', name: 'Stok Rezerve', sortOrder: 30 },
    { code: 'fulfilled', name: 'Tamamlandı', sortOrder: 40 },
    { code: 'cancelled', name: 'İptal', sortOrder: 50 },
  ],
  purchase_order_statuses: [
    { code: 'draft', name: 'Taslak', sortOrder: 10 },
    { code: 'pending_manager_approval', name: 'Yönetici Onayı Bekliyor', sortOrder: 15 },
    { code: 'sent', name: 'Tedarikçiye Gönderildi', sortOrder: 20 },
    { code: 'approved', name: 'Onaylandı', sortOrder: 30 },
    { code: 'in_transit', name: 'Yolda', sortOrder: 40 },
    { code: 'received', name: 'Teslim Alındı', sortOrder: 50 },
    { code: 'cancelled', name: 'İptal', sortOrder: 60 },
  ],
  opportunity_statuses: [
    { code: 'open', name: 'Açık', sortOrder: 10 },
    { code: 'won', name: 'Kazanıldı', sortOrder: 20 },
    { code: 'lost', name: 'Kaybedildi', sortOrder: 30 },
    { code: 'on_hold', name: 'Beklemede', sortOrder: 40 },
  ],
  activity_types: [
    { code: 'incoming_call', name: 'Gelen Arama', sortOrder: 10 },
    { code: 'outgoing_call', name: 'Giden Arama', sortOrder: 20 },
    { code: 'customer_visit', name: 'Müşteri Ziyareti', sortOrder: 30 },
    { code: 'online_meeting', name: 'Çevrimiçi Toplantı', sortOrder: 40 },
    { code: 'showroom_meeting', name: 'Showroom Toplantısı', sortOrder: 50 },
    { code: 'email', name: 'E-posta', sortOrder: 60 },
    { code: 'whatsapp', name: 'WhatsApp', sortOrder: 70 },
    { code: 'note', name: 'Yorum', sortOrder: 80 },
  ],
  company_relation_types: [
    { code: 'customer', name: 'Müşteri', sortOrder: 10 },
    { code: 'supplier', name: 'Tedarikçi', sortOrder: 20 },
    { code: 'supplier_customer', name: 'Tedarikçi + Müşteri', sortOrder: 30 },
    { code: 'competitor', name: 'Rakip', sortOrder: 40 },
  ],
  company_statuses: [
    { code: 'potential', name: 'Potansiyel', sortOrder: 10 },
    { code: 'active', name: 'Aktif Müşteri', sortOrder: 20 },
    { code: 'passive', name: 'Pasif', sortOrder: 30 },
    { code: 'blacklist', name: 'Kara Liste', sortOrder: 40 },
  ],
  company_groups: [
    { code: 'cnc', name: 'CNC', sortOrder: 1 },
    { code: 'universal', name: 'Üniversal', sortOrder: 2 },
    { code: 'sac_isleme', name: 'Sac İşleme', sortOrder: 3 },
    { code: 'a_group', name: 'A Grubu (Sıcak/Büyük)', sortOrder: 10 },
    { code: 'b_group', name: 'B Grubu (Orta)', sortOrder: 20 },
    { code: 'dealer_second_hand', name: 'Bayi / 2. Elci', sortOrder: 30 },
    { code: 'potential_cnc_customer', name: 'Potansiyel CNC Müşterisi', sortOrder: 40 },
    { code: 'kobi', name: 'KOBİ', sortOrder: 10 },
    { code: 'kurumsal', name: 'Kurumsal', sortOrder: 20 },
    { code: 'kamu', name: 'Kamu', sortOrder: 30 },
  ],
  company_sectors: [
    { code: 'kalip', name: 'Kalıp', sortOrder: 10 },
    { code: 'otomotiv', name: 'Otomotiv', sortOrder: 20 },
    { code: 'makine_imalat', name: 'Makine İmalat', sortOrder: 30 },
    { code: 'plastik', name: 'Plastik', sortOrder: 40 },
    { code: 'metal_isleme', name: 'Metal İşleme', sortOrder: 50 },
    { code: 'savunma', name: 'Savunma', sortOrder: 60 },
    { code: 'havacilik', name: 'Havacılık', sortOrder: 70 },
    { code: 'egitim', name: 'Eğitim', sortOrder: 80 },
    { code: 'diger', name: 'Diğer', sortOrder: 90 },
  ],
  contact_sources: [
    { code: 'maktek_2024_fair', name: 'MAKTEK 2024 / Fuar', sortOrder: 1 },
    { code: 'musiad_expo', name: 'MÜSİAD Expo', sortOrder: 2 },
    { code: 'harun_aslanbay_reference', name: 'Harun Aslanbay (Referans)', sortOrder: 3 },
    { code: 'website_inbound_call', name: 'Web Sitesi / Gelen Çağrı', sortOrder: 4 },
    { code: 'cold_call_field', name: 'Soğuk Arama / Saha', sortOrder: 5 },
    { code: 'visit', name: 'Ziyaret', sortOrder: 6 },
    { code: 'email', name: 'Mail', sortOrder: 1 },
    { code: 'phone', name: 'Telefon', sortOrder: 2 },
    { code: 'dealer', name: 'Bayi', sortOrder: 3 },
    { code: 'digital_market', name: 'Dijital Pazar', sortOrder: 4 },
    { code: 'musiad', name: 'MÜSİAD', sortOrder: 5 },
    { code: 'reference', name: 'Referans', sortOrder: 10 },
    { code: 'website', name: 'Web Sitesi', sortOrder: 20 },
    { code: 'fair', name: 'Fuar', sortOrder: 30 },
    { code: 'social_media', name: 'Sosyal Medya', sortOrder: 40 },
    { code: 'cold_call', name: 'Soğuk Arama', sortOrder: 50 },
    { code: 'other', name: 'Diğer', sortOrder: 60 },
  ],
  tax_offices: [
    { code: 'bursa_nilufer', name: 'Nilüfer Vergi Dairesi', province: 'Bursa', sortOrder: 10 },
    { code: 'bursa_osmangazi', name: 'Osmangazi Vergi Dairesi', province: 'Bursa', sortOrder: 20 },
    { code: 'bursa_yildirim', name: 'Yıldırım Vergi Dairesi', province: 'Bursa', sortOrder: 30 },
    { code: 'istanbul_avcilar', name: 'Avcılar Vergi Dairesi', province: 'İstanbul', sortOrder: 40 },
    { code: 'istanbul_beylikduzu', name: 'Beylikdüzü Vergi Dairesi', province: 'İstanbul', sortOrder: 50 },
    { code: 'istanbul_kadikoy', name: 'Kadıköy Vergi Dairesi', province: 'İstanbul', sortOrder: 60 },
    { code: 'istanbul_pendik', name: 'Pendik Vergi Dairesi', province: 'İstanbul', sortOrder: 70 },
    { code: 'kocaeli_izmit', name: 'İzmit Vergi Dairesi', province: 'Kocaeli', sortOrder: 80 },
    { code: 'ankara_baskent', name: 'Başkent Vergi Dairesi', province: 'Ankara', sortOrder: 90 },
    { code: 'izmir_konak', name: 'Konak Vergi Dairesi', province: 'İzmir', sortOrder: 100 },
  ],
  decision_roles: [
    { code: 'owner', name: 'Sahip / Yönetici', sortOrder: 10 },
    { code: 'technical', name: 'Teknik Karar Verici', sortOrder: 20 },
    { code: 'financial', name: 'Finansal Karar Verici', sortOrder: 30 },
    { code: 'influencer', name: 'Etkileyici', sortOrder: 40 },
    { code: 'user', name: 'Kullanıcı', sortOrder: 50 },
  ],
  product_groups: [
    { code: 'CNC', name: 'CNC', sortOrder: 10 },
    { code: 'UNIVERSAL', name: 'Üniversal', sortOrder: 20 },
    { code: 'SAC_ISLEME', name: 'Sac İşleme', sortOrder: 30 },
    { code: 'YEDEK_PARCA', name: 'Yedek Parça', sortOrder: 40 },
    { code: 'AKSESUAR', name: 'Aksesuar', sortOrder: 50 },
  ],
  product_categories: [
    { code: 'TEZGAH', name: 'Tezgah', sortOrder: 10 },
    { code: 'OPSIYONEL_DONANIM', name: 'Opsiyonel Donanım', sortOrder: 20 },
    { code: 'YEDEK_PARCA', name: 'Yedek Parça', sortOrder: 30 },
    { code: 'AKSESUAR', name: 'Aksesuar', sortOrder: 40 },
    { code: 'EVRAK', name: 'Evrak', sortOrder: 50 },
    { code: 'IDARI_MALZEME', name: 'İdari Malzeme', sortOrder: 60 },
    { code: 'ISCILIK', name: 'İşçilik', sortOrder: 70 },
    { code: 'YAZILIM', name: 'Yazılım', sortOrder: 80 },
    { code: 'HIZMET', name: 'Hizmet', sortOrder: 90 },
  ],
  product_subcategories: [
    { code: 'ISLEME_MERKEZI', name: 'İşleme Merkezi', sortOrder: 10 },
    { code: 'TORNA', name: 'Torna', sortOrder: 20 },
    { code: 'TASLAMA', name: 'Taşlama', sortOrder: 30 },
    { code: 'KAYIK', name: 'Kayık (EDM)', sortOrder: 40 },
  ],
  product_types: [
    { code: 'DIK_ISLEME_MERKEZI', name: 'CNC Dik İşleme Merkezi', sortOrder: 10 },
    { code: 'KOPRU_TIPI_ISLEME_MERKEZI', name: 'CNC Köprü Tipi İşleme Merkezi', sortOrder: 20 },
    { code: 'CNC_TORNA', name: 'CNC Torna Tezgahı', sortOrder: 30 },
    { code: 'CNC_DIK_ISLEME_MERKEZ', name: 'CNC Dik İşleme Merkezi', sortOrder: 50 },
    { code: 'CNC_KOPRU_TIPI_ISLEME_MERKEZI', name: 'CNC Köprü Tipi İşleme Merkezi', sortOrder: 70 },
    { code: 'CNC_5_EKSEN_ISLEME_MERKEZI', name: 'CNC 5 Eksen İşleme Merkezi', sortOrder: 80 },
    { code: 'CNC_TAPPING_CENTER', name: 'CNC Tapping Center', sortOrder: 90 },
    { code: 'CNC_YATAY_TORNA_TEZGAHI', name: 'CNC Yatay Torna Tezgahı', sortOrder: 100 },
    { code: 'CNC_DIK_TORNA_TEZGAHI', name: 'CNC Dik Torna Tezgahı', sortOrder: 110 },
    { code: 'ELEKTRONIK', name: 'Elektronik', sortOrder: 120 },
    { code: 'ELEKTRIK', name: 'Elektrik', sortOrder: 130 },
    { code: 'MEKANIK', name: 'Mekanik', sortOrder: 140 },
    { code: 'KONTROL_UNITESI', name: 'Kontrol Ünitesi', sortOrder: 150 },
    { code: 'SPINDLE', name: 'Spindle', sortOrder: 160 },
    { code: 'ISCILIK', name: 'İşçilik', sortOrder: 170 },
    { code: 'YAG_SIYIRICI', name: 'Yağ Sıyırıcı', sortOrder: 180 },
    { code: 'TUTUCU_TAKIMLAR', name: 'Tutucu & Takımlar', sortOrder: 190 },
    { code: 'DIVIZOR', name: 'Divizör', sortOrder: 200 },
    { code: 'REGULATOR', name: 'Regülatör', sortOrder: 210 },
  ],
  product_spec_groups: [
    { code: 'TABLA', name: 'Tabla', sortOrder: 10 },
    { code: 'EKSENLER', name: 'Eksenler', sortOrder: 20 },
    { code: 'FENER_MILI', name: 'Fener Mili', sortOrder: 30 },
    { code: 'MOTORLAR', name: 'Motorlar', sortOrder: 40 },
    { code: 'TAKIM_DEGISTIRICI', name: 'Takım Değiştirici', sortOrder: 50 },
    { code: 'KAPASITE', name: 'Kapasite', sortOrder: 60 },
    { code: 'TARET', name: 'Taret', sortOrder: 70 },
    { code: 'KARSI_PUNTA', name: 'Karşı Punta', sortOrder: 80 },
    { code: 'KARSI_AYNA', name: 'Karşı Ayna', sortOrder: 82 },
    { code: 'CANLI_TAKIM', name: 'Canlı Takım', sortOrder: 84 },
    { code: 'GENEL', name: 'Genel', sortOrder: 90 },
  ],
  equipment_types: [
    { code: 'standart', name: 'Standart Donanım', sortOrder: 10 },
    { code: 'opsiyonel', name: 'Opsiyonel Donanım', sortOrder: 20 },
    { code: 'promosyon', name: 'Promosyon', sortOrder: 30 },
  ],
  inventory_statuses: [
    { code: 'available', name: 'Stokta', sortOrder: 10 },
    { code: 'reserved', name: 'Rezerve', sortOrder: 20 },
    { code: 'sold', name: 'Satıldı', sortOrder: 30 },
    { code: 'in_transit', name: 'Yolda', sortOrder: 40 },
    { code: 'damaged', name: 'Hasarlı', sortOrder: 50 },
    { code: 'returned', name: 'İade', sortOrder: 60 },
  ],
  stock_location_statuses: [
    { code: 'on_road', name: 'Yolda', sortOrder: 10 },
    { code: 'at_port', name: 'Limanda', sortOrder: 20 },
    { code: 'at_warehouse', name: 'Depoda', sortOrder: 30 },
    { code: 'at_customer', name: 'Müşteride', sortOrder: 40 },
  ],
  file_document_types: [
    { code: 'product_image', name: 'Ürün Görseli', sortOrder: 10 },
    { code: 'company_logo', name: 'Firma Logosu', sortOrder: 15 },
    { code: 'signature', name: 'İmza Görseli', sortOrder: 18 },
    { code: 'quote_pdf', name: 'Teklif PDF', sortOrder: 20 },
    { code: 'external_quote', name: 'Dış Teklif', sortOrder: 25 },
    { code: 'proforma_pdf', name: 'Proforma PDF', sortOrder: 30 },
    { code: 'contract_pdf', name: 'Sözleşme PDF', sortOrder: 40 },
    { code: 'commercial_invoice_pdf', name: 'Ticari Fatura PDF', sortOrder: 50 },
    { code: 'accounting_invoice_pdf', name: 'Muhasebe Faturası PDF', sortOrder: 55 },
    { code: 'stock_document', name: 'Stok Belgesi', sortOrder: 60 },
    { code: 'service_document', name: 'Servis Belgesi', sortOrder: 70 },
    { code: 'delivery_form', name: 'Teslim Formu', sortOrder: 72 },
    { code: 'installation_form', name: 'Kurulum Formu', sortOrder: 74 },
    { code: 'activity_document', name: 'Aktivite Dosyası', sortOrder: 80 },
    { code: 'service_complaint_evidence', name: 'Servis Şikayet Kanıtı', sortOrder: 85 },
    { code: 'customs_document', name: 'Gümrük Belgesi', sortOrder: 90 },
    { code: 'other', name: 'Diğer', sortOrder: 100 },
  ],
  storage_providers: [
    { code: 'minio', name: 'MinIO (dev)', sortOrder: 10 },
    { code: 'supabase', name: 'Supabase Storage', sortOrder: 20 },
    { code: 's3', name: 'AWS S3', sortOrder: 30 },
    { code: 'r2', name: 'Cloudflare R2', sortOrder: 40 },
  ],
  payment_statuses: [
    { code: 'pending', name: 'Beklemede', sortOrder: 10 },
    { code: 'partial', name: 'Kısmi Ödendi', sortOrder: 20 },
    { code: 'paid', name: 'Ödendi', sortOrder: 30 },
    { code: 'overdue', name: 'Vadesi Geçti', sortOrder: 40 },
    { code: 'cancelled', name: 'İptal', sortOrder: 50 },
  ],
  service_ticket_statuses: [
    { code: 'open', name: 'Açık', sortOrder: 10 },
    { code: 'in_progress', name: 'İşlemde', sortOrder: 20 },
    { code: 'waiting_customer', name: 'Müşteri Bekleniyor', sortOrder: 30 },
    { code: 'resolved', name: 'Çözüldü', sortOrder: 40 },
    { code: 'closed', name: 'Kapatıldı', sortOrder: 50 },
  ],
  installation_statuses: [
    { code: 'scheduled', name: 'Planlandı', sortOrder: 10 },
    { code: 'in_progress', name: 'Devam Ediyor', sortOrder: 20 },
    { code: 'completed', name: 'Tamamlandı', sortOrder: 30 },
    { code: 'cancelled', name: 'İptal', sortOrder: 40 },
  ],
  currencies: [
    { code: 'USD', name: 'ABD Doları', sortOrder: 10 },
    { code: 'EUR', name: 'Euro', sortOrder: 20 },
    { code: 'TRY', name: 'Türk Lirası', sortOrder: 30 },
    { code: 'GBP', name: 'İngiliz Sterlini', sortOrder: 40 },
  ],
  units: [
    { code: 'adet', name: 'Adet', sortOrder: 10 },
    { code: 'kg', name: 'Kilogram', sortOrder: 20 },
    { code: 'm', name: 'Metre', sortOrder: 30 },
    { code: 'saat', name: 'Saat', sortOrder: 40 },
    { code: 'paket', name: 'Paket', sortOrder: 50 },
  ],
  warranty_statuses: [
    { code: 'active', name: 'Aktif Garanti', sortOrder: 10 },
    { code: 'expired', name: 'Garanti Süresi Doldu', sortOrder: 20 },
    { code: 'extended', name: 'Uzatılmış Garanti', sortOrder: 30 },
    { code: 'void', name: 'Garanti İptal', sortOrder: 40 },
  ],
  shipment_statuses: [
    { code: 'preparing', name: 'Hazırlanıyor', sortOrder: 10 },
    { code: 'in_transit', name: 'Yolda', sortOrder: 20 },
    { code: 'at_customs', name: 'Gümrükte', sortOrder: 30 },
    { code: 'cleared', name: 'Gümrük Onaylı', sortOrder: 40 },
    { code: 'delivered', name: 'Teslim Edildi', sortOrder: 50 },
  ],
  shipment_package_units: [
    { code: 'package', name: 'Paket', sortOrder: 10 },
    { code: 'pallet', name: 'Palet', sortOrder: 20 },
    { code: 'crate', name: 'Sandık', sortOrder: 30 },
    { code: 'box', name: 'Koli', sortOrder: 40 },
    { code: 'piece', name: 'Adet', sortOrder: 50 },
  ],
  invoice_statuses: [
    { code: 'draft', name: 'Taslak', sortOrder: 10 },
    { code: 'issued', name: 'Düzenlendi', sortOrder: 20 },
    { code: 'paid', name: 'Ödendi', sortOrder: 30 },
    { code: 'cancelled', name: 'İptal', sortOrder: 40 },
  ],
  proforma_statuses: [
    { code: 'draft', name: 'Taslak', sortOrder: 10 },
    { code: 'sent', name: 'Gönderildi', sortOrder: 20 },
    { code: 'accepted', name: 'Kabul Edildi', sortOrder: 30 },
    { code: 'cancelled', name: 'İptal', sortOrder: 40 },
  ],
  contract_statuses: [
    { code: 'draft', name: 'Taslak', sortOrder: 10 },
    { code: 'signed', name: 'İmzalandı', sortOrder: 20 },
    { code: 'fulfilled', name: 'Tamamlandı', sortOrder: 30 },
    { code: 'cancelled', name: 'İptal', sortOrder: 40 },
  ],
} as const;

/**
 * Permission matrix per role.
 * Wildcard `*` means all actions on a resource.
 */
export const rolePermissionMatrix: Record<string, Record<string, string[] | '*'>> = {
  super_admin: { '*': '*' },
  admin: {
    tenants: ['read', 'update'],
    users: '*',
    roles: ['read'],
    departments: '*',
    divisions: '*',
    companies: '*',
    contacts: '*',
    leads: '*',
    lead_assignment_rules: '*',
    opportunities: '*',
    activities: '*',
    calendar: '*',
    competitors: '*',
    brands: '*',
    products: '*',
    product_specs: '*',
    price_lists: '*',
    warehouses: '*',
    inventory: '*',
    customer_devices: '*',
    quotes: '*',
    sales_orders: '*',
    proformas: '*',
    contracts: '*',
    commercial_invoices: '*',
    accounting_invoices: '*',
    purchase_orders: ['read', 'create', 'update', 'delete', 'export'],
    shipments: '*',
    installations: '*',
    service_tickets: '*',
    receivables: '*',
    payments: '*',
    files: '*',
    reports: ['read', 'export'],
    meta: '*',
    meta_campaigns: '*',
    meta_messages: '*',
    meta_audiences: '*',
    meta_catalogs: '*',
    audit: ['read'],
  },
  sales: {
    calendar: '*',
    companies: '*',
    contacts: '*',
    leads: '*',
    lead_assignment_rules: ['read'],
    // A+ onayları ayrı bir rol/yetkiyle kullanıcıya atanır; standart satış
    // rolü tüm fırsatları yönetebilir ancak onay veremez/reddedemez.
    opportunities: ['read', 'create', 'update', 'delete', 'export'],
    activities: '*',
    competitors: ['read', 'create'],
    brands: ['read'],
    products: ['read'],
    product_specs: ['read'],
    price_lists: ['read'],
    quotes: ['read', 'create', 'update', 'delete'],
    sales_orders: ['read', 'create', 'update', 'delete'],
    // Satış hattı proforma → sözleşme → ticari fatura aşamalarından geçer ve her
    // aşama bu belgenin oluşturulmasını şart koşar; satış rolü bu belgeleri
    // üretebilmelidir.
    proformas: ['read', 'create', 'update', 'delete'],
    contracts: ['read', 'create', 'update', 'delete'],
    commercial_invoices: ['read', 'create', 'update', 'delete'],
    accounting_invoices: ['read', 'create', 'update', 'delete'],
    files: ['read', 'create'],
    reports: ['read', 'export'],
    // Satış ekibi performansı ve gelen talepleri görür, konuşmaları yönetebilir.
    // Bütçe/kampanya, kitle ve katalog yazma işlemleri yönetici yetkisinde kalır.
    meta: ['read'],
    meta_campaigns: ['read'],
    meta_messages: ['read', 'create', 'update'],
    meta_audiences: ['read'],
    meta_catalogs: ['read'],
    inventory: ['read'],
    // Departmanlar arası görünürlük: stok gibi makineler de (fiyat listeleri hariç)
    // tüm departman rollerince okunabilir.
    customer_devices: ['read'],
  },
  service: {
    calendar: '*',
    companies: ['read'],
    contacts: ['read'],
    activities: ['read', 'convert'],
    customer_devices: '*',
    installations: '*',
    service_tickets: '*',
    shipments: '*',
    files: ['read', 'create'],
    products: ['read'],
    inventory: ['read'],
  },
  finance: {
    calendar: '*',
    companies: ['read'],
    contacts: ['read'],
    quotes: ['read', 'approve', 'reject'],
    sales_orders: ['read', 'approve', 'reject'],
    purchase_orders: ['read'],
    // Ticari faturayı kestiği belge zincirini (proforma/sözleşme) görebilmeli.
    proformas: ['read'],
    contracts: ['read'],
    commercial_invoices: '*',
    accounting_invoices: '*',
    receivables: '*',
    payments: '*',
    files: ['read', 'create'],
    reports: ['read', 'export'],
    // Departmanlar arası görünürlük: stok ve makineler (fiyat listeleri hariç)
    // finans tarafından da okunabilir.
    inventory: ['read'],
    customer_devices: ['read'],
    products: ['read'],
  },
  stock: {
    calendar: '*',
    // Sevkiyat/teslimat için hedef firma ve ilgili kişiyi okuyabilmeli.
    companies: ['read'],
    contacts: ['read'],
    // Stok rezervasyonu/sevkiyatın bağlı olduğu satış fırsatını görebilmeli.
    opportunities: ['read'],
    warehouses: '*',
    inventory: '*',
    customer_devices: ['read', 'update', 'delete'],
    products: ['read'],
    purchase_orders: ['read', 'create', 'update', 'delete', 'export'],
    sales_orders: ['read', 'update'],
    files: ['read', 'create'],
    shipments: '*',
  },
  readonly: {
    '*': ['read'],
  },
};

export const allRoles = ['super_admin', 'admin', 'sales', 'service', 'finance', 'stock', 'readonly'] as const;
